#ifndef STINGRAY_TOOLKIT_MACRO_H
#define STINGRAY_TOOLKIT_MACRO_H


#define MK_PARAM(...)	__VA_ARGS__

#define TO_STRING_IMPL(...) #__VA_ARGS__
#define TO_STRING(...) TO_STRING_IMPL(__VA_ARGS__)

#define TOOLKIT_CAT_IMPL(A, B)	A##B
#define TOOLKIT_CAT(A, B)	TOOLKIT_CAT_IMPL(A, B)

#define TOOLKIT_NARGS_SEQ(Dummy_, _1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,N,...) N
#define TOOLKIT_NARGS(...) TOOLKIT_NARGS_SEQ(Dummy_, ##__VA_ARGS__, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)


#define DETAIL_FIRST_ARG(_0, ...) _0
#define DETAIL_SECOND_ARG(_0, _1, ...) _1

#define DETAIL_NOT_IMPL(...) DETAIL_SECOND_ARG(__VA_ARGS__, 0, Dummy_)
#define DETAIL_NOT_0 ~, 1

#define TOOLKIT_NOT(A) DETAIL_NOT_IMPL(TOOLKIT_CAT(DETAIL_NOT_, A))


#define DETAIL_COMPL_0 1
#define DETAIL_COMPL_1 0

#define TOOLKIT_COMPL(A) TOOLKIT_CAT(DETAIL_COMPL_, A)


#define TOOLKIT_BOOL(A) TOOLKIT_COMPL(TOOLKIT_NOT(A))


#define DETAIL_COMMA_IF_0
#define DETAIL_COMMA_IF_1 ,

#define TOOLKIT_COMMA_IF(A) TOOLKIT_CAT(DETAIL_COMMA_IF_, TOOLKIT_BOOL(A))


#define TOOLKIT_EMPTY()
#define TOOLKIT_DEFER(A) A TOOLKIT_EMPTY()
#define TOOLKIT_EXPAND(...) __VA_ARGS__


#define DETAIL_PREPEND_ARGS_0(...) __VA_ARGS__
#define DETAIL_PREPEND_ARGS_1(...) ~, DETAIL_PREPEND_ARGS_0(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_2(...) ~, DETAIL_PREPEND_ARGS_1(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_3(...) ~, DETAIL_PREPEND_ARGS_2(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_4(...) ~, DETAIL_PREPEND_ARGS_3(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_5(...) ~, DETAIL_PREPEND_ARGS_4(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_6(...) ~, DETAIL_PREPEND_ARGS_5(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_7(...) ~, DETAIL_PREPEND_ARGS_6(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_8(...) ~, DETAIL_PREPEND_ARGS_7(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_9(...) ~, DETAIL_PREPEND_ARGS_8(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_10(...) ~, DETAIL_PREPEND_ARGS_9(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_11(...) ~, DETAIL_PREPEND_ARGS_10(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_12(...) ~, DETAIL_PREPEND_ARGS_11(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_13(...) ~, DETAIL_PREPEND_ARGS_12(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_14(...) ~, DETAIL_PREPEND_ARGS_13(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_15(...) ~, DETAIL_PREPEND_ARGS_14(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_16(...) ~, DETAIL_PREPEND_ARGS_15(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_17(...) ~, DETAIL_PREPEND_ARGS_16(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_18(...) ~, DETAIL_PREPEND_ARGS_17(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_19(...) ~, DETAIL_PREPEND_ARGS_18(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_20(...) ~, DETAIL_PREPEND_ARGS_19(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_21(...) ~, DETAIL_PREPEND_ARGS_20(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_22(...) ~, DETAIL_PREPEND_ARGS_21(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_23(...) ~, DETAIL_PREPEND_ARGS_22(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_24(...) ~, DETAIL_PREPEND_ARGS_23(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_25(...) ~, DETAIL_PREPEND_ARGS_24(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_26(...) ~, DETAIL_PREPEND_ARGS_25(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_27(...) ~, DETAIL_PREPEND_ARGS_26(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_28(...) ~, DETAIL_PREPEND_ARGS_27(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_29(...) ~, DETAIL_PREPEND_ARGS_28(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_30(...) ~, DETAIL_PREPEND_ARGS_29(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_31(...) ~, DETAIL_PREPEND_ARGS_30(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_32(...) ~, DETAIL_PREPEND_ARGS_31(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_33(...) ~, DETAIL_PREPEND_ARGS_32(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_34(...) ~, DETAIL_PREPEND_ARGS_33(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_35(...) ~, DETAIL_PREPEND_ARGS_34(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_36(...) ~, DETAIL_PREPEND_ARGS_35(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_37(...) ~, DETAIL_PREPEND_ARGS_36(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_38(...) ~, DETAIL_PREPEND_ARGS_37(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_39(...) ~, DETAIL_PREPEND_ARGS_38(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_40(...) ~, DETAIL_PREPEND_ARGS_39(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_41(...) ~, DETAIL_PREPEND_ARGS_40(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_42(...) ~, DETAIL_PREPEND_ARGS_41(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_43(...) ~, DETAIL_PREPEND_ARGS_42(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_44(...) ~, DETAIL_PREPEND_ARGS_43(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_45(...) ~, DETAIL_PREPEND_ARGS_44(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_46(...) ~, DETAIL_PREPEND_ARGS_45(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_47(...) ~, DETAIL_PREPEND_ARGS_46(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_48(...) ~, DETAIL_PREPEND_ARGS_47(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_49(...) ~, DETAIL_PREPEND_ARGS_48(__VA_ARGS__)
#define DETAIL_PREPEND_ARGS_50(...) ~, DETAIL_PREPEND_ARGS_49(__VA_ARGS__)


#define DETAIL_CROP_ARGS_0(...) __VA_ARGS__
#define DETAIL_CROP_ARGS_1(_0, ...) DETAIL_CROP_ARGS_0(__VA_ARGS__)
#define DETAIL_CROP_ARGS_2(_0, ...) DETAIL_CROP_ARGS_1(__VA_ARGS__)
#define DETAIL_CROP_ARGS_3(_0, ...) DETAIL_CROP_ARGS_2(__VA_ARGS__)
#define DETAIL_CROP_ARGS_4(_0, ...) DETAIL_CROP_ARGS_3(__VA_ARGS__)
#define DETAIL_CROP_ARGS_5(_0, ...) DETAIL_CROP_ARGS_4(__VA_ARGS__)
#define DETAIL_CROP_ARGS_6(_0, ...) DETAIL_CROP_ARGS_5(__VA_ARGS__)
#define DETAIL_CROP_ARGS_7(_0, ...) DETAIL_CROP_ARGS_6(__VA_ARGS__)
#define DETAIL_CROP_ARGS_8(_0, ...) DETAIL_CROP_ARGS_7(__VA_ARGS__)
#define DETAIL_CROP_ARGS_9(_0, ...) DETAIL_CROP_ARGS_8(__VA_ARGS__)
#define DETAIL_CROP_ARGS_10(_0, ...) DETAIL_CROP_ARGS_9(__VA_ARGS__)
#define DETAIL_CROP_ARGS_11(_0, ...) DETAIL_CROP_ARGS_10(__VA_ARGS__)
#define DETAIL_CROP_ARGS_12(_0, ...) DETAIL_CROP_ARGS_11(__VA_ARGS__)
#define DETAIL_CROP_ARGS_13(_0, ...) DETAIL_CROP_ARGS_12(__VA_ARGS__)
#define DETAIL_CROP_ARGS_14(_0, ...) DETAIL_CROP_ARGS_13(__VA_ARGS__)
#define DETAIL_CROP_ARGS_15(_0, ...) DETAIL_CROP_ARGS_14(__VA_ARGS__)
#define DETAIL_CROP_ARGS_16(_0, ...) DETAIL_CROP_ARGS_15(__VA_ARGS__)
#define DETAIL_CROP_ARGS_17(_0, ...) DETAIL_CROP_ARGS_16(__VA_ARGS__)
#define DETAIL_CROP_ARGS_18(_0, ...) DETAIL_CROP_ARGS_17(__VA_ARGS__)
#define DETAIL_CROP_ARGS_19(_0, ...) DETAIL_CROP_ARGS_18(__VA_ARGS__)
#define DETAIL_CROP_ARGS_20(_0, ...) DETAIL_CROP_ARGS_19(__VA_ARGS__)
#define DETAIL_CROP_ARGS_21(_0, ...) DETAIL_CROP_ARGS_20(__VA_ARGS__)
#define DETAIL_CROP_ARGS_22(_0, ...) DETAIL_CROP_ARGS_21(__VA_ARGS__)
#define DETAIL_CROP_ARGS_23(_0, ...) DETAIL_CROP_ARGS_22(__VA_ARGS__)
#define DETAIL_CROP_ARGS_24(_0, ...) DETAIL_CROP_ARGS_23(__VA_ARGS__)
#define DETAIL_CROP_ARGS_25(_0, ...) DETAIL_CROP_ARGS_24(__VA_ARGS__)
#define DETAIL_CROP_ARGS_26(_0, ...) DETAIL_CROP_ARGS_25(__VA_ARGS__)
#define DETAIL_CROP_ARGS_27(_0, ...) DETAIL_CROP_ARGS_26(__VA_ARGS__)
#define DETAIL_CROP_ARGS_28(_0, ...) DETAIL_CROP_ARGS_27(__VA_ARGS__)
#define DETAIL_CROP_ARGS_29(_0, ...) DETAIL_CROP_ARGS_28(__VA_ARGS__)
#define DETAIL_CROP_ARGS_30(_0, ...) DETAIL_CROP_ARGS_29(__VA_ARGS__)
#define DETAIL_CROP_ARGS_31(_0, ...) DETAIL_CROP_ARGS_30(__VA_ARGS__)
#define DETAIL_CROP_ARGS_32(_0, ...) DETAIL_CROP_ARGS_31(__VA_ARGS__)
#define DETAIL_CROP_ARGS_33(_0, ...) DETAIL_CROP_ARGS_32(__VA_ARGS__)
#define DETAIL_CROP_ARGS_34(_0, ...) DETAIL_CROP_ARGS_33(__VA_ARGS__)
#define DETAIL_CROP_ARGS_35(_0, ...) DETAIL_CROP_ARGS_34(__VA_ARGS__)
#define DETAIL_CROP_ARGS_36(_0, ...) DETAIL_CROP_ARGS_35(__VA_ARGS__)
#define DETAIL_CROP_ARGS_37(_0, ...) DETAIL_CROP_ARGS_36(__VA_ARGS__)
#define DETAIL_CROP_ARGS_38(_0, ...) DETAIL_CROP_ARGS_37(__VA_ARGS__)
#define DETAIL_CROP_ARGS_39(_0, ...) DETAIL_CROP_ARGS_38(__VA_ARGS__)
#define DETAIL_CROP_ARGS_40(_0, ...) DETAIL_CROP_ARGS_39(__VA_ARGS__)
#define DETAIL_CROP_ARGS_41(_0, ...) DETAIL_CROP_ARGS_40(__VA_ARGS__)
#define DETAIL_CROP_ARGS_42(_0, ...) DETAIL_CROP_ARGS_41(__VA_ARGS__)
#define DETAIL_CROP_ARGS_43(_0, ...) DETAIL_CROP_ARGS_42(__VA_ARGS__)
#define DETAIL_CROP_ARGS_44(_0, ...) DETAIL_CROP_ARGS_43(__VA_ARGS__)
#define DETAIL_CROP_ARGS_45(_0, ...) DETAIL_CROP_ARGS_44(__VA_ARGS__)
#define DETAIL_CROP_ARGS_46(_0, ...) DETAIL_CROP_ARGS_45(__VA_ARGS__)
#define DETAIL_CROP_ARGS_47(_0, ...) DETAIL_CROP_ARGS_46(__VA_ARGS__)
#define DETAIL_CROP_ARGS_48(_0, ...) DETAIL_CROP_ARGS_47(__VA_ARGS__)
#define DETAIL_CROP_ARGS_49(_0, ...) DETAIL_CROP_ARGS_48(__VA_ARGS__)
#define DETAIL_CROP_ARGS_50(_0, ...) DETAIL_CROP_ARGS_49(__VA_ARGS__)


#define DETAIL_NATURAL_SEQUENCE 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, Dummy_, Dummy_


#define TOOLKIT_ADD(A, B) TOOLKIT_EXPAND(TOOLKIT_DEFER(DETAIL_FIRST_ARG)(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_CROP_ARGS_, A))(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_CROP_ARGS_, B))(DETAIL_NATURAL_SEQUENCE))))))

#define TOOLKIT_INC(A) TOOLKIT_ADD(A, 1)


#define TOOLKIT_SUB(A, B) TOOLKIT_EXPAND(TOOLKIT_DEFER(DETAIL_FIRST_ARG)(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_CROP_ARGS_, A))(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_PREPEND_ARGS_, B))(DETAIL_NATURAL_SEQUENCE))))))

#define TOOLKIT_DEC(A) TOOLKIT_SUB(A, 1)


#define DETAIL_REPEAT_IMPL_0(MacroName, Data)
#define DETAIL_REPEAT_IMPL_1(MacroName, Data) DETAIL_REPEAT_IMPL_0 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 0, Data)
#define DETAIL_REPEAT_IMPL_2(MacroName, Data) DETAIL_REPEAT_IMPL_1 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 1, Data)
#define DETAIL_REPEAT_IMPL_3(MacroName, Data) DETAIL_REPEAT_IMPL_2 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 2, Data)
#define DETAIL_REPEAT_IMPL_4(MacroName, Data) DETAIL_REPEAT_IMPL_3 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 3, Data)
#define DETAIL_REPEAT_IMPL_5(MacroName, Data) DETAIL_REPEAT_IMPL_4 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 4, Data)
#define DETAIL_REPEAT_IMPL_6(MacroName, Data) DETAIL_REPEAT_IMPL_5 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 5, Data)
#define DETAIL_REPEAT_IMPL_7(MacroName, Data) DETAIL_REPEAT_IMPL_6 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 6, Data)
#define DETAIL_REPEAT_IMPL_8(MacroName, Data) DETAIL_REPEAT_IMPL_7 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 7, Data)
#define DETAIL_REPEAT_IMPL_9(MacroName, Data) DETAIL_REPEAT_IMPL_8 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 8, Data)
#define DETAIL_REPEAT_IMPL_10(MacroName, Data) DETAIL_REPEAT_IMPL_9 (MK_PARAM(MacroName), MK_PARAM(Data)) MacroName( 9, Data)
#define DETAIL_REPEAT_IMPL_11(MacroName, Data) DETAIL_REPEAT_IMPL_10(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(10, Data)
#define DETAIL_REPEAT_IMPL_12(MacroName, Data) DETAIL_REPEAT_IMPL_11(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(11, Data)
#define DETAIL_REPEAT_IMPL_13(MacroName, Data) DETAIL_REPEAT_IMPL_12(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(12, Data)
#define DETAIL_REPEAT_IMPL_14(MacroName, Data) DETAIL_REPEAT_IMPL_13(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(13, Data)
#define DETAIL_REPEAT_IMPL_15(MacroName, Data) DETAIL_REPEAT_IMPL_14(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(14, Data)
#define DETAIL_REPEAT_IMPL_16(MacroName, Data) DETAIL_REPEAT_IMPL_15(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(15, Data)
#define DETAIL_REPEAT_IMPL_17(MacroName, Data) DETAIL_REPEAT_IMPL_16(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(16, Data)
#define DETAIL_REPEAT_IMPL_18(MacroName, Data) DETAIL_REPEAT_IMPL_17(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(17, Data)
#define DETAIL_REPEAT_IMPL_19(MacroName, Data) DETAIL_REPEAT_IMPL_18(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(18, Data)
#define DETAIL_REPEAT_IMPL_20(MacroName, Data) DETAIL_REPEAT_IMPL_19(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(19, Data)
#define DETAIL_REPEAT_IMPL_21(MacroName, Data) DETAIL_REPEAT_IMPL_20(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(20, Data)
#define DETAIL_REPEAT_IMPL_22(MacroName, Data) DETAIL_REPEAT_IMPL_21(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(21, Data)
#define DETAIL_REPEAT_IMPL_23(MacroName, Data) DETAIL_REPEAT_IMPL_22(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(22, Data)
#define DETAIL_REPEAT_IMPL_24(MacroName, Data) DETAIL_REPEAT_IMPL_23(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(23, Data)
#define DETAIL_REPEAT_IMPL_25(MacroName, Data) DETAIL_REPEAT_IMPL_24(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(24, Data)
#define DETAIL_REPEAT_IMPL_26(MacroName, Data) DETAIL_REPEAT_IMPL_25(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(25, Data)
#define DETAIL_REPEAT_IMPL_27(MacroName, Data) DETAIL_REPEAT_IMPL_26(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(26, Data)
#define DETAIL_REPEAT_IMPL_28(MacroName, Data) DETAIL_REPEAT_IMPL_27(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(27, Data)
#define DETAIL_REPEAT_IMPL_29(MacroName, Data) DETAIL_REPEAT_IMPL_28(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(28, Data)
#define DETAIL_REPEAT_IMPL_30(MacroName, Data) DETAIL_REPEAT_IMPL_29(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(29, Data)
#define DETAIL_REPEAT_IMPL_31(MacroName, Data) DETAIL_REPEAT_IMPL_30(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(30, Data)
#define DETAIL_REPEAT_IMPL_32(MacroName, Data) DETAIL_REPEAT_IMPL_31(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(31, Data)
#define DETAIL_REPEAT_IMPL_33(MacroName, Data) DETAIL_REPEAT_IMPL_32(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(32, Data)
#define DETAIL_REPEAT_IMPL_34(MacroName, Data) DETAIL_REPEAT_IMPL_33(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(33, Data)
#define DETAIL_REPEAT_IMPL_35(MacroName, Data) DETAIL_REPEAT_IMPL_34(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(34, Data)
#define DETAIL_REPEAT_IMPL_36(MacroName, Data) DETAIL_REPEAT_IMPL_35(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(35, Data)
#define DETAIL_REPEAT_IMPL_37(MacroName, Data) DETAIL_REPEAT_IMPL_36(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(36, Data)
#define DETAIL_REPEAT_IMPL_38(MacroName, Data) DETAIL_REPEAT_IMPL_37(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(37, Data)
#define DETAIL_REPEAT_IMPL_39(MacroName, Data) DETAIL_REPEAT_IMPL_38(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(38, Data)
#define DETAIL_REPEAT_IMPL_40(MacroName, Data) DETAIL_REPEAT_IMPL_39(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(39, Data)
#define DETAIL_REPEAT_IMPL_41(MacroName, Data) DETAIL_REPEAT_IMPL_40(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(40, Data)
#define DETAIL_REPEAT_IMPL_42(MacroName, Data) DETAIL_REPEAT_IMPL_41(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(41, Data)
#define DETAIL_REPEAT_IMPL_43(MacroName, Data) DETAIL_REPEAT_IMPL_42(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(42, Data)
#define DETAIL_REPEAT_IMPL_44(MacroName, Data) DETAIL_REPEAT_IMPL_43(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(43, Data)
#define DETAIL_REPEAT_IMPL_45(MacroName, Data) DETAIL_REPEAT_IMPL_44(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(44, Data)
#define DETAIL_REPEAT_IMPL_46(MacroName, Data) DETAIL_REPEAT_IMPL_45(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(45, Data)
#define DETAIL_REPEAT_IMPL_47(MacroName, Data) DETAIL_REPEAT_IMPL_46(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(46, Data)
#define DETAIL_REPEAT_IMPL_48(MacroName, Data) DETAIL_REPEAT_IMPL_47(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(47, Data)
#define DETAIL_REPEAT_IMPL_49(MacroName, Data) DETAIL_REPEAT_IMPL_48(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(48, Data)
#define DETAIL_REPEAT_IMPL_50(MacroName, Data) DETAIL_REPEAT_IMPL_49(MK_PARAM(MacroName), MK_PARAM(Data)) MacroName(49, Data)

#define TOOLKIT_REPEAT(RepetitionsCount, MacroName, Data) TOOLKIT_CAT(DETAIL_REPEAT_IMPL_, RepetitionsCount)(MK_PARAM(MacroName), MK_PARAM(Data))

#if 0
#define ______TOOLKIT_MACRO_FOR_0(FUNC)
#define ______TOOLKIT_MACRO_FOR_1(FUNC) FUNC(1)
#define ______TOOLKIT_MACRO_FOR_2(FUNC) TOOLKIT_MACRO_FOR_1(FUNC) FUNC(2)
#define ______TOOLKIT_MACRO_FOR_3(FUNC) TOOLKIT_MACRO_FOR_2(FUNC) FUNC(3)
#define ______TOOLKIT_MACRO_FOR_4(FUNC) TOOLKIT_MACRO_FOR_3(FUNC) FUNC(4)

#define ______TOOLKIT_MACRO_FOR(N, FUNC) TOOLKIT_MACRO_FOR_##N(FUNC)
#endif


#endif
