#ifndef STINGRAY_TOOLKIT_MACRO_H
#define STINGRAY_TOOLKIT_MACRO_H


#define MK_PARAM(...)	__VA_ARGS__

#define TO_STRING_IMPL(...) #__VA_ARGS__
#define TO_STRING(...) TO_STRING_IMPL(__VA_ARGS__)

#define TOOLKIT_CAT_IMPL(A, B)	A##B
#define TOOLKIT_CAT(A, B)	TOOLKIT_CAT_IMPL(A, B)

#define TOOLKIT_NARGS_SEQ(Dummy_, _1,_2,_3,_4,_5,_6,_7,_8,_9,_10,_11,_12,_13,_14,_15,_16,_17,_18,_19,_20,_21,_22,_23,_24,_25,_26,_27,_28,_29,_30,N,...) N
#define TOOLKIT_NARGS(...) TOOLKIT_NARGS_SEQ(Dummy_, ##__VA_ARGS__, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0)


#define DETAIL_FIRST_ARG(_0, ...) _0
#define DETAIL_SECOND_ARG(_0, _1, ...) _1

#define DETAIL_NOT_IMPL(...) DETAIL_SECOND_ARG(__VA_ARGS__, 0, Dummy_)
#define DETAIL_NOT_0 ~, 1

#define TOOLKIT_NOT(A) DETAIL_NOT_IMPL(TOOLKIT_CAT(DETAIL_NOT_, A))


#define DETAIL_COMPL_0 1
#define DETAIL_COMPL_1 0

#define TOOLKIT_COMPL(A) TOOLKIT_CAT(DETAIL_COMPL_, A)


#define TOOLKIT_BOOL(A) TOOLKIT_COMPL(TOOLKIT_NOT(A))


#define DETAIL_COMMA_IF_0
#define DETAIL_COMMA_IF_1 ,

#define TOOLKIT_COMMA_IF(A) TOOLKIT_CAT(DETAIL_COMMA_IF_, TOOLKIT_BOOL(A))


#define TOOLKIT_EMPTY()
#define TOOLKIT_DEFER(A) A TOOLKIT_EMPTY()
#define TOOLKIT_EXPAND(...) __VA_ARGS__


#define DETAIL_CROP_ARGS_0(...) __VA_ARGS__
#define DETAIL_CROP_ARGS_1(_0, ...) DETAIL_CROP_ARGS_0(__VA_ARGS__)
#define DETAIL_CROP_ARGS_2(_0, ...) DETAIL_CROP_ARGS_1(__VA_ARGS__)
#define DETAIL_CROP_ARGS_3(_0, ...) DETAIL_CROP_ARGS_2(__VA_ARGS__)
#define DETAIL_CROP_ARGS_4(_0, ...) DETAIL_CROP_ARGS_3(__VA_ARGS__)
#define DETAIL_CROP_ARGS_5(_0, ...) DETAIL_CROP_ARGS_4(__VA_ARGS__)
#define DETAIL_CROP_ARGS_6(_0, ...) DETAIL_CROP_ARGS_5(__VA_ARGS__)
#define DETAIL_CROP_ARGS_7(_0, ...) DETAIL_CROP_ARGS_6(__VA_ARGS__)
#define DETAIL_CROP_ARGS_8(_0, ...) DETAIL_CROP_ARGS_7(__VA_ARGS__)
#define DETAIL_CROP_ARGS_9(_0, ...) DETAIL_CROP_ARGS_8(__VA_ARGS__)
#define DETAIL_CROP_ARGS_10(_0, ...) DETAIL_CROP_ARGS_9(__VA_ARGS__)
#define DETAIL_CROP_ARGS_11(_0, ...) DETAIL_CROP_ARGS_10(__VA_ARGS__)
#define DETAIL_CROP_ARGS_12(_0, ...) DETAIL_CROP_ARGS_11(__VA_ARGS__)
#define DETAIL_CROP_ARGS_13(_0, ...) DETAIL_CROP_ARGS_12(__VA_ARGS__)
#define DETAIL_CROP_ARGS_14(_0, ...) DETAIL_CROP_ARGS_13(__VA_ARGS__)
#define DETAIL_CROP_ARGS_15(_0, ...) DETAIL_CROP_ARGS_14(__VA_ARGS__)
#define DETAIL_CROP_ARGS_16(_0, ...) DETAIL_CROP_ARGS_15(__VA_ARGS__)
#define DETAIL_CROP_ARGS_17(_0, ...) DETAIL_CROP_ARGS_16(__VA_ARGS__)
#define DETAIL_CROP_ARGS_18(_0, ...) DETAIL_CROP_ARGS_17(__VA_ARGS__)
#define DETAIL_CROP_ARGS_19(_0, ...) DETAIL_CROP_ARGS_18(__VA_ARGS__)
#define DETAIL_CROP_ARGS_20(_0, ...) DETAIL_CROP_ARGS_19(__VA_ARGS__)
#define DETAIL_CROP_ARGS_21(_0, ...) DETAIL_CROP_ARGS_20(__VA_ARGS__)
#define DETAIL_CROP_ARGS_22(_0, ...) DETAIL_CROP_ARGS_21(__VA_ARGS__)
#define DETAIL_CROP_ARGS_23(_0, ...) DETAIL_CROP_ARGS_22(__VA_ARGS__)
#define DETAIL_CROP_ARGS_24(_0, ...) DETAIL_CROP_ARGS_23(__VA_ARGS__)
#define DETAIL_CROP_ARGS_25(_0, ...) DETAIL_CROP_ARGS_24(__VA_ARGS__)
#define DETAIL_CROP_ARGS_26(_0, ...) DETAIL_CROP_ARGS_25(__VA_ARGS__)
#define DETAIL_CROP_ARGS_27(_0, ...) DETAIL_CROP_ARGS_26(__VA_ARGS__)
#define DETAIL_CROP_ARGS_28(_0, ...) DETAIL_CROP_ARGS_27(__VA_ARGS__)
#define DETAIL_CROP_ARGS_29(_0, ...) DETAIL_CROP_ARGS_28(__VA_ARGS__)
#define DETAIL_CROP_ARGS_30(_0, ...) DETAIL_CROP_ARGS_29(__VA_ARGS__)
#define DETAIL_CROP_ARGS_31(_0, ...) DETAIL_CROP_ARGS_30(__VA_ARGS__)
#define DETAIL_CROP_ARGS_32(_0, ...) DETAIL_CROP_ARGS_31(__VA_ARGS__)
#define DETAIL_CROP_ARGS_33(_0, ...) DETAIL_CROP_ARGS_32(__VA_ARGS__)
#define DETAIL_CROP_ARGS_34(_0, ...) DETAIL_CROP_ARGS_33(__VA_ARGS__)
#define DETAIL_CROP_ARGS_35(_0, ...) DETAIL_CROP_ARGS_34(__VA_ARGS__)
#define DETAIL_CROP_ARGS_36(_0, ...) DETAIL_CROP_ARGS_35(__VA_ARGS__)
#define DETAIL_CROP_ARGS_37(_0, ...) DETAIL_CROP_ARGS_36(__VA_ARGS__)
#define DETAIL_CROP_ARGS_38(_0, ...) DETAIL_CROP_ARGS_37(__VA_ARGS__)
#define DETAIL_CROP_ARGS_39(_0, ...) DETAIL_CROP_ARGS_38(__VA_ARGS__)
#define DETAIL_CROP_ARGS_40(_0, ...) DETAIL_CROP_ARGS_39(__VA_ARGS__)
#define DETAIL_CROP_ARGS_41(_0, ...) DETAIL_CROP_ARGS_40(__VA_ARGS__)
#define DETAIL_CROP_ARGS_42(_0, ...) DETAIL_CROP_ARGS_41(__VA_ARGS__)
#define DETAIL_CROP_ARGS_43(_0, ...) DETAIL_CROP_ARGS_42(__VA_ARGS__)
#define DETAIL_CROP_ARGS_44(_0, ...) DETAIL_CROP_ARGS_43(__VA_ARGS__)
#define DETAIL_CROP_ARGS_45(_0, ...) DETAIL_CROP_ARGS_44(__VA_ARGS__)
#define DETAIL_CROP_ARGS_46(_0, ...) DETAIL_CROP_ARGS_45(__VA_ARGS__)
#define DETAIL_CROP_ARGS_47(_0, ...) DETAIL_CROP_ARGS_46(__VA_ARGS__)
#define DETAIL_CROP_ARGS_48(_0, ...) DETAIL_CROP_ARGS_47(__VA_ARGS__)
#define DETAIL_CROP_ARGS_49(_0, ...) DETAIL_CROP_ARGS_48(__VA_ARGS__)
#define DETAIL_CROP_ARGS_50(_0, ...) DETAIL_CROP_ARGS_49(__VA_ARGS__)


#define DETAIL_NATURAL_SEQUENCE 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, Dummy_, Dummy_


#define TOOLKIT_ADD(A, B) TOOLKIT_EXPAND(TOOLKIT_DEFER(DETAIL_FIRST_ARG)(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_CROP_ARGS_, A))(TOOLKIT_EXPAND(TOOLKIT_DEFER(TOOLKIT_CAT(DETAIL_CROP_ARGS_, B))(DETAIL_NATURAL_SEQUENCE))))))

#define TOOLKIT_INC(A) TOOLKIT_ADD(A, 1)


#if 0
#define ______TOOLKIT_MACRO_FOR_0(FUNC)
#define ______TOOLKIT_MACRO_FOR_1(FUNC) FUNC(1)
#define ______TOOLKIT_MACRO_FOR_2(FUNC) TOOLKIT_MACRO_FOR_1(FUNC) FUNC(2)
#define ______TOOLKIT_MACRO_FOR_3(FUNC) TOOLKIT_MACRO_FOR_2(FUNC) FUNC(3)
#define ______TOOLKIT_MACRO_FOR_4(FUNC) TOOLKIT_MACRO_FOR_3(FUNC) FUNC(4)

#define ______TOOLKIT_MACRO_FOR(N, FUNC) TOOLKIT_MACRO_FOR_##N(FUNC)
#endif


#endif
