var searchData=
[
  ['ibytestream',['IByteStream',['../dc/d02/structstingray_1_1IByteStream.html',1,'stingray']]],
  ['icancellationhandler',['ICancellationHandler',['../d1/d3e/structstingray_1_1ICancellationHandler.html',1,'stingray']]],
  ['icancellationtoken',['ICancellationToken',['../d3/d34/structstingray_1_1ICancellationToken.html',1,'stingray']]],
  ['icircularbuffer',['ICircularBuffer',['../db/daa/structstingray_1_1ICircularBuffer.html',1,'stingray']]],
  ['icloneable',['ICloneable',['../d4/d8e/structstingray_1_1ICloneable.html',1,'stingray']]],
  ['icollection',['ICollection',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['ICollection&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20keytype_5f_20_3e',['ICollection&lt; KeyType_ &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20keyvaluepair_3c_20keytype_5f_2c_20valuetype_5f_20_3e_20_3e',['ICollection&lt; KeyValuePair&lt; KeyType_, ValueType_ &gt; &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20keyvaluepair_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e_20_3e',['ICollection&lt; KeyValuePair&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt; &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20keyvaluepair_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e_20_3e',['ICollection&lt; KeyValuePair&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt; &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['ICollection&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20valuetype_5f_20_3e',['ICollection&lt; ValueType_ &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icollection_3c_20wrapped_5f_3a_3avaluetype_20_3e',['ICollection&lt; Wrapped_::ValueType &gt;',['../dd/d59/structstingray_1_1ICollection.html',1,'stingray']]],
  ['icomparable',['IComparable',['../dc/d21/structstingray_1_1IComparable.html',1,'stingray']]],
  ['icreator',['ICreator',['../d8/d49/structstingray_1_1ICreator.html',1,'stingray']]],
  ['icreator_3c_20interfacetype_20_3e',['ICreator&lt; InterfaceType &gt;',['../d8/d49/structstingray_1_1ICreator.html',1,'stingray']]],
  ['idatabuffer',['IDataBuffer',['../de/df4/structstingray_1_1IDataBuffer.html',1,'stingray']]],
  ['idataconsumer',['IDataConsumer',['../d7/d26/structstingray_1_1IDataConsumer.html',1,'stingray']]],
  ['idatasource',['IDataSource',['../d6/d2b/structstingray_1_1IDataSource.html',1,'stingray']]],
  ['identitymapper',['IdentityMapper',['../d0/df8/structstingray_1_1IdentityMapper.html',1,'stingray']]],
  ['idictionary',['IDictionary',['../d4/d84/structstingray_1_1IDictionary.html',1,'stingray']]],
  ['idictionary_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IDictionary&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt;',['../d4/d84/structstingray_1_1IDictionary.html',1,'stingray']]],
  ['idictionary_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['IDictionary&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../d4/d84/structstingray_1_1IDictionary.html',1,'stingray']]],
  ['idictionarytransaction',['IDictionaryTransaction',['../da/d56/structstingray_1_1IDictionaryTransaction.html',1,'stingray']]],
  ['idictionarytransaction_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['IDictionaryTransaction&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../da/d56/structstingray_1_1IDictionaryTransaction.html',1,'stingray']]],
  ['ienumerable',['IEnumerable',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IEnumerable&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20desttype_20_3e',['IEnumerable&lt; DestType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20enumeratedt_20_3e',['IEnumerable&lt; EnumeratedT &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20function_5finfo_3c_20functor_5f_20_3e_3a_3arettype_3a_3avaluetype_3a_3aitemtype_20_3e',['IEnumerable&lt; function_info&lt; Functor_ &gt;::RetType::ValueType::ItemType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20keytype_5f_20_3e',['IEnumerable&lt; KeyType_ &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20keyvaluepair_3c_20keytype_5f_2c_20valuetype_5f_20_3e_20_3e',['IEnumerable&lt; KeyValuePair&lt; KeyType_, ValueType_ &gt; &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20keyvaluepair_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e_20_3e',['IEnumerable&lt; KeyValuePair&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt; &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20keyvaluepair_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e_20_3e',['IEnumerable&lt; KeyValuePair&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt; &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20pairtype_20_3e',['IEnumerable&lt; PairType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IEnumerable&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20srctype_20_3e',['IEnumerable&lt; SrcType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20valuetype_20_3e',['IEnumerable&lt; ValueType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20valuetype_5f_20_3e',['IEnumerable&lt; ValueType_ &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerable_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IEnumerable&lt; Wrapped_::ValueType &gt;',['../d9/d53/structstingray_1_1IEnumerable.html',1,'stingray']]],
  ['ienumerator',['IEnumerator',['../d6/d58/structstingray_1_1IEnumerator.html',1,'stingray']]],
  ['ienumerator_3c_20desttype_20_3e',['IEnumerator&lt; DestType &gt;',['../d6/d58/structstingray_1_1IEnumerator.html',1,'stingray']]],
  ['ienumerator_3c_20enumeratedt_20_3e',['IEnumerator&lt; EnumeratedT &gt;',['../d6/d58/structstingray_1_1IEnumerator.html',1,'stingray']]],
  ['ienumerator_3c_20srctype_20_3e',['IEnumerator&lt; SrcType &gt;',['../d6/d58/structstingray_1_1IEnumerator.html',1,'stingray']]],
  ['ienumerator_3c_20stingray_3a_3adetail_3a_3agetitemtypefromitemdecl_3c_20itemdeclfunc_20_3e_3a_3avaluet_20_3e',['IEnumerator&lt; stingray::Detail::GetItemTypeFromItemDecl&lt; ItemDeclFunc &gt;::ValueT &gt;',['../d6/d58/structstingray_1_1IEnumerator.html',1,'stingray']]],
  ['if',['If',['../d4/d63/structstingray_1_1If.html',1,'stingray']]],
  ['if_3c_20false_2c_20iftype_2c_20elsetype_20_3e',['If&lt; false, IfType, ElseType &gt;',['../d9/d3c/structstingray_1_1If_3_01false_00_01IfType_00_01ElseType_01_4.html',1,'stingray']]],
  ['if_3c_20isconst_3c_20chartype_20_3e_3a_3avalue_2c_20const_20char_20_2a_2c_20char_20_2a_20_3e',['If&lt; IsConst&lt; CharType &gt;::Value, const char *, char * &gt;',['../d4/d63/structstingray_1_1If.html',1,'stingray']]],
  ['if_3c_20true_2c_20iftype_2c_20elsetype_20_3e',['If&lt; true, IfType, ElseType &gt;',['../d6/d4d/structstingray_1_1If_3_01true_00_01IfType_00_01ElseType_01_4.html',1,'stingray']]],
  ['ifactoryobject',['IFactoryObject',['../d9/dd5/structstingray_1_1IFactoryObject.html',1,'stingray']]],
  ['ifactoryobjectcreator',['IFactoryObjectCreator',['../db/d14/structstingray_1_1FactoryContext_1_1IFactoryObjectCreator.html',1,'stingray::FactoryContext']]],
  ['ifuzzyequatable',['IFuzzyEquatable',['../d8/d1c/structstingray_1_1IFuzzyEquatable.html',1,'stingray']]],
  ['iinputbytestream',['IInputByteStream',['../d6/d5a/structstingray_1_1IInputByteStream.html',1,'stingray']]],
  ['ilist',['IList',['../df/d3c/structstingray_1_1IList.html',1,'stingray']]],
  ['ilist_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IList&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../df/d3c/structstingray_1_1IList.html',1,'stingray']]],
  ['ilist_3c_20valuetype_5f_20_3e',['IList&lt; ValueType_ &gt;',['../df/d3c/structstingray_1_1IList.html',1,'stingray']]],
  ['ilist_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IList&lt; Wrapped_::ValueType &gt;',['../df/d3c/structstingray_1_1IList.html',1,'stingray']]],
  ['iloggersink',['ILoggerSink',['../dc/df3/structstingray_1_1ILoggerSink.html',1,'stingray']]],
  ['implicitcaster',['ImplicitCaster',['../db/da1/structstingray_1_1ImplicitCaster.html',1,'stingray']]],
  ['inc',['Inc',['../da/d6e/structstingray_1_1BasicAtomicInt.html#a82f935d6bbd2f6ac6db4372a88de9a25',1,'stingray::BasicAtomicInt']]],
  ['indexoftypelistitem',['IndexOfTypeListItem',['../d1/de9/structstingray_1_1IndexOfTypeListItem.html',1,'stingray']]],
  ['indexoftypelistitem_3c_20typelist_2c_20typename_20typelist_3a_3avaluet_2c_200_20_3e',['IndexOfTypeListItem&lt; TypeList, typename TypeList::ValueT, 0 &gt;',['../da/d7b/structstingray_1_1IndexOfTypeListItem_3_01TypeList_00_01typename_01TypeList_1_1ValueT_00_010_01_4.html',1,'stingray']]],
  ['indexoftypelistitem_3c_20typelist_2c_20typename_20typelist_3a_3avaluet_2c_20index_5f_20_3e',['IndexOfTypeListItem&lt; TypeList, typename TypeList::ValueT, Index_ &gt;',['../d8/d76/structstingray_1_1IndexOfTypeListItem_3_01TypeList_00_01typename_01TypeList_1_1ValueT_00_01Index___01_4.html',1,'stingray']]],
  ['indexoftypelistitem_3c_20typelistendnode_2c_20t_2c_20index_5f_20_3e',['IndexOfTypeListItem&lt; TypeListEndNode, T, Index_ &gt;',['../d7/d5f/structstingray_1_1IndexOfTypeListItem_3_01TypeListEndNode_00_01T_00_01Index___01_4.html',1,'stingray']]],
  ['indexoutofrangeexception',['IndexOutOfRangeException',['../d9/def/classstingray_1_1IndexOutOfRangeException.html',1,'stingray']]],
  ['inherits',['Inherits',['../d3/d72/classstingray_1_1Inherits.html',1,'stingray']]],
  ['inherits1paramtemplate',['Inherits1ParamTemplate',['../df/dc7/classstingray_1_1Inherits1ParamTemplate.html',1,'stingray']]],
  ['inherits1paramtemplate_3c_20t_2c_20ilist_20_3e',['Inherits1ParamTemplate&lt; T, IList &gt;',['../df/dc7/classstingray_1_1Inherits1ParamTemplate.html',1,'stingray']]],
  ['inherits1paramtemplate_3c_20t_2c_20ireadonlylist_20_3e',['Inherits1ParamTemplate&lt; T, IReadonlyList &gt;',['../df/dc7/classstingray_1_1Inherits1ParamTemplate.html',1,'stingray']]],
  ['inherits1paramtemplate_3c_20t_2c_20ireadonlyset_20_3e',['Inherits1ParamTemplate&lt; T, IReadonlySet &gt;',['../df/dc7/classstingray_1_1Inherits1ParamTemplate.html',1,'stingray']]],
  ['inherits1paramtemplate_3c_20t_2c_20iset_20_3e',['Inherits1ParamTemplate&lt; T, ISet &gt;',['../df/dc7/classstingray_1_1Inherits1ParamTemplate.html',1,'stingray']]],
  ['inherits2paramtemplate',['Inherits2ParamTemplate',['../df/d93/classstingray_1_1Inherits2ParamTemplate.html',1,'stingray']]],
  ['inherits2paramtemplate_3c_20t_2c_20idictionary_20_3e',['Inherits2ParamTemplate&lt; T, IDictionary &gt;',['../df/d93/classstingray_1_1Inherits2ParamTemplate.html',1,'stingray']]],
  ['inherits2paramtemplate_3c_20t_2c_20ireadonlydictionary_20_3e',['Inherits2ParamTemplate&lt; T, IReadonlyDictionary &gt;',['../df/d93/classstingray_1_1Inherits2ParamTemplate.html',1,'stingray']]],
  ['inheritsidictionary',['InheritsIDictionary',['../d8/dcf/structstingray_1_1InheritsIDictionary.html',1,'stingray']]],
  ['inheritsilist',['InheritsIList',['../d8/dec/structstingray_1_1InheritsIList.html',1,'stingray']]],
  ['inheritsireadonlydictionary',['InheritsIReadonlyDictionary',['../d4/dec/structstingray_1_1InheritsIReadonlyDictionary.html',1,'stingray']]],
  ['inheritsireadonlylist',['InheritsIReadonlyList',['../d8/d30/structstingray_1_1InheritsIReadonlyList.html',1,'stingray']]],
  ['inheritsireadonlyset',['InheritsIReadonlySet',['../d8/dae/structstingray_1_1InheritsIReadonlySet.html',1,'stingray']]],
  ['inheritsiset',['InheritsISet',['../d8/d6b/structstingray_1_1InheritsISet.html',1,'stingray']]],
  ['inplace_5fvector',['inplace_vector',['../d6/d0a/classstingray_1_1inplace__vector.html',1,'stingray']]],
  ['instanceofpredicate',['InstanceOfPredicate',['../de/d71/structstingray_1_1InstanceOfPredicate.html',1,'stingray']]],
  ['instanceoftester',['InstanceOfTester',['../d0/d9f/structstingray_1_1InstanceOfTester.html',1,'stingray']]],
  ['instanceoftester_3c_20light_5fshared_5fptr_3c_20t_20_3e_20_3e',['InstanceOfTester&lt; light_shared_ptr&lt; T &gt; &gt;',['../d5/d97/structstingray_1_1InstanceOfTester_3_01light__shared__ptr_3_01T_01_4_01_4.html',1,'stingray']]],
  ['instanceoftester_3c_20shared_5fptr_3c_20t_20_3e_20_3e',['InstanceOfTester&lt; shared_ptr&lt; T &gt; &gt;',['../d0/d60/structstingray_1_1InstanceOfTester_3_01shared__ptr_3_01T_01_4_01_4.html',1,'stingray']]],
  ['instanceoftester_3c_20t_20_2a_20_3e',['InstanceOfTester&lt; T * &gt;',['../da/d82/structstingray_1_1InstanceOfTester_3_01T_01_5_01_4.html',1,'stingray']]],
  ['integerbuilder',['IntegerBuilder',['../dc/d08/classstingray_1_1IntegerBuilder.html',1,'stingray']]],
  ['integersequencegenerator',['IntegerSequenceGenerator',['../d0/dce/classstingray_1_1IntegerSequenceGenerator.html',1,'stingray']]],
  ['integral_5fconstant',['integral_constant',['../d2/da8/structstingray_1_1integral__constant.html',1,'stingray']]],
  ['integral_5fconstant_5fless',['integral_constant_less',['../d5/dc9/structstingray_1_1integral__constant__less.html',1,'stingray']]],
  ['intermediatedatabuffer',['IntermediateDataBuffer',['../d2/df8/classstingray_1_1IntermediateDataBuffer.html',1,'stingray']]],
  ['intervaltree',['IntervalTree',['../d9/dbf/classstingray_1_1IntervalTree.html',1,'stingray']]],
  ['intrusivelist',['IntrusiveList',['../d3/d38/classstingray_1_1IntrusiveList.html',1,'stingray']]],
  ['intrusivelist_3c_20sessionimpl_20_3e',['IntrusiveList&lt; SessionImpl &gt;',['../d3/d38/classstingray_1_1IntrusiveList.html',1,'stingray']]],
  ['intrusivelistnodedata',['IntrusiveListNodeData',['../d6/d80/classstingray_1_1IntrusiveListNodeData.html',1,'stingray']]],
  ['inttotype',['IntToType',['../d9/da0/structstingray_1_1IntToType.html',1,'stingray']]],
  ['inttraits',['IntTraits',['../d6/de9/structstingray_1_1IntTraits.html',1,'stingray']]],
  ['inttype',['IntType',['../d1/de7/structstingray_1_1IntType.html',1,'stingray']]],
  ['invalidcastexception',['InvalidCastException',['../d6/d0f/structstingray_1_1InvalidCastException.html',1,'stingray']]],
  ['invalidoperationexception',['InvalidOperationException',['../d6/dd1/structstingray_1_1InvalidOperationException.html',1,'stingray']]],
  ['invoker',['Invoker',['../dd/d08/structstingray_1_1signal_1_1Invoker.html#aaadbad8feb9229b3bba89d6c3cee634b',1,'stingray::signal::Invoker::Invoker(const signal &amp;theSignal)'],['../dd/d08/structstingray_1_1signal_1_1Invoker.html#aaadbad8feb9229b3bba89d6c3cee634b',1,'stingray::signal::Invoker::Invoker(const signal &amp;theSignal)'],['../d6/d76/structstingray_1_1signal.html#a1c4ce6d33ce4d480413b69c035601623',1,'stingray::signal::invoker() const '],['../d6/d76/structstingray_1_1signal.html#a1c4ce6d33ce4d480413b69c035601623',1,'stingray::signal::invoker() const ']]],
  ['invoker',['Invoker',['../dd/d08/structstingray_1_1signal_1_1Invoker.html',1,'stingray::signal']]],
  ['iobjectistreamprivate',['IObjectIStreamPrivate',['../d0/d17/structstingray_1_1IObjectIStreamPrivate.html',1,'stingray']]],
  ['iobjectostreamprivate',['IObjectOStreamPrivate',['../dd/d32/structstingray_1_1IObjectOStreamPrivate.html',1,'stingray']]],
  ['iobjectserializator',['IObjectSerializator',['../d5/d15/structstingray_1_1IObjectSerializator.html',1,'stingray']]],
  ['iobservabledictionary',['IObservableDictionary',['../d5/d1c/structstingray_1_1IObservableDictionary.html',1,'stingray']]],
  ['iobservabledictionary_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IObservableDictionary&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt;',['../d5/d1c/structstingray_1_1IObservableDictionary.html',1,'stingray']]],
  ['iobservabledictionary_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['IObservableDictionary&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../d5/d1c/structstingray_1_1IObservableDictionary.html',1,'stingray']]],
  ['iobservablelist',['IObservableList',['../da/d7e/structstingray_1_1IObservableList.html',1,'stingray']]],
  ['iobservablelist_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IObservableList&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../da/d7e/structstingray_1_1IObservableList.html',1,'stingray']]],
  ['iobservablelist_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IObservableList&lt; Wrapped_::ValueType &gt;',['../da/d7e/structstingray_1_1IObservableList.html',1,'stingray']]],
  ['iobservableset',['IObservableSet',['../dd/d46/structstingray_1_1IObservableSet.html',1,'stingray']]],
  ['iobservableset_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IObservableSet&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../dd/d46/structstingray_1_1IObservableSet.html',1,'stingray']]],
  ['iobservableset_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IObservableSet&lt; Wrapped_::ValueType &gt;',['../dd/d46/structstingray_1_1IObservableSet.html',1,'stingray']]],
  ['ioutputbytestream',['IOutputByteStream',['../d1/dda/structstingray_1_1IOutputByteStream.html',1,'stingray']]],
  ['ipacketconsumer',['IPacketConsumer',['../d7/d0c/structstingray_1_1IPacketConsumer.html',1,'stingray']]],
  ['ipacketsource',['IPacketSource',['../dd/df7/structstingray_1_1IPacketSource.html',1,'stingray']]],
  ['ipacketsource_3c_20emptytype_20_3e',['IPacketSource&lt; EmptyType &gt;',['../dd/df7/structstingray_1_1IPacketSource.html',1,'stingray']]],
  ['ipage',['IPage',['../d1/dcd/structstingray_1_1PagedBuffer_1_1IPage.html',1,'stingray::PagedBuffer']]],
  ['ipipe',['IPipe',['../db/d47/structstingray_1_1IPipe.html',1,'stingray']]],
  ['ireadonlydictionary',['IReadonlyDictionary',['../dc/dd9/structstingray_1_1IReadonlyDictionary.html',1,'stingray']]],
  ['ireadonlydictionary_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlyDictionary&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt;',['../dc/dd9/structstingray_1_1IReadonlyDictionary.html',1,'stingray']]],
  ['ireadonlydictionary_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlyDictionary&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../dc/dd9/structstingray_1_1IReadonlyDictionary.html',1,'stingray']]],
  ['ireadonlylist',['IReadonlyList',['../da/dd6/structstingray_1_1IReadonlyList.html',1,'stingray']]],
  ['ireadonlylist_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlyList&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../da/dd6/structstingray_1_1IReadonlyList.html',1,'stingray']]],
  ['ireadonlylist_3c_20valuetype_5f_20_3e',['IReadonlyList&lt; ValueType_ &gt;',['../da/dd6/structstingray_1_1IReadonlyList.html',1,'stingray']]],
  ['ireadonlylist_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlyList&lt; Wrapped_::ValueType &gt;',['../da/dd6/structstingray_1_1IReadonlyList.html',1,'stingray']]],
  ['ireadonlyobservabledictionary',['IReadonlyObservableDictionary',['../d7/d76/structstingray_1_1IReadonlyObservableDictionary.html',1,'stingray']]],
  ['ireadonlyobservabledictionary_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlyObservableDictionary&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt;',['../d7/d76/structstingray_1_1IReadonlyObservableDictionary.html',1,'stingray']]],
  ['ireadonlyobservabledictionary_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlyObservableDictionary&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../d7/d76/structstingray_1_1IReadonlyObservableDictionary.html',1,'stingray']]],
  ['ireadonlyobservablelist',['IReadonlyObservableList',['../d0/d2d/structstingray_1_1IReadonlyObservableList.html',1,'stingray']]],
  ['ireadonlyobservablelist_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlyObservableList&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../d0/d2d/structstingray_1_1IReadonlyObservableList.html',1,'stingray']]],
  ['ireadonlyobservablelist_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlyObservableList&lt; Wrapped_::ValueType &gt;',['../d0/d2d/structstingray_1_1IReadonlyObservableList.html',1,'stingray']]],
  ['ireadonlyobservableset',['IReadonlyObservableSet',['../d1/db9/structstingray_1_1IReadonlyObservableSet.html',1,'stingray']]],
  ['ireadonlyobservableset_3c_20keytype_5f_20_3e',['IReadonlyObservableSet&lt; KeyType_ &gt;',['../d1/db9/structstingray_1_1IReadonlyObservableSet.html',1,'stingray']]],
  ['ireadonlyobservableset_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlyObservableSet&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../d1/db9/structstingray_1_1IReadonlyObservableSet.html',1,'stingray']]],
  ['ireadonlyobservableset_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlyObservableSet&lt; Wrapped_::ValueType &gt;',['../d1/db9/structstingray_1_1IReadonlyObservableSet.html',1,'stingray']]],
  ['ireadonlyset',['IReadonlySet',['../dc/db6/structstingray_1_1IReadonlySet.html',1,'stingray']]],
  ['ireadonlyset_3c_20keytype_5f_20_3e',['IReadonlySet&lt; KeyType_ &gt;',['../dc/db6/structstingray_1_1IReadonlySet.html',1,'stingray']]],
  ['ireadonlyset_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IReadonlySet&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../dc/db6/structstingray_1_1IReadonlySet.html',1,'stingray']]],
  ['ireadonlyset_3c_20valuetype_5f_20_3e',['IReadonlySet&lt; ValueType_ &gt;',['../dc/db6/structstingray_1_1IReadonlySet.html',1,'stingray']]],
  ['ireadonlyset_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IReadonlySet&lt; Wrapped_::ValueType &gt;',['../dc/db6/structstingray_1_1IReadonlySet.html',1,'stingray']]],
  ['ireversableenumerable',['IReversableEnumerable',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20arraylist_3c_20valuetype_5f_20_3e_3a_3avaluetype_20_3e',['IReversableEnumerable&lt; ArrayList&lt; ValueType_ &gt;::ValueType &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20keytype_5f_20_3e',['IReversableEnumerable&lt; KeyType_ &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20keyvaluepair_3c_20keytype_5f_2c_20valuetype_5f_20_3e_20_3e',['IReversableEnumerable&lt; KeyValuePair&lt; KeyType_, ValueType_ &gt; &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20keyvaluepair_3c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3akeytype_2c_20mapdictionary_3c_20keytype_5f_2c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e_20_3e',['IReversableEnumerable&lt; KeyValuePair&lt; MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::KeyType, MapDictionary&lt; KeyType_, ValueType_, CompareType_ &gt;::ValueType &gt; &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20keyvaluepair_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e_20_3e',['IReversableEnumerable&lt; KeyValuePair&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt; &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['IReversableEnumerable&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20valuetype_5f_20_3e',['IReversableEnumerable&lt; ValueType_ &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['ireversableenumerable_3c_20wrapped_5f_3a_3avaluetype_20_3e',['IReversableEnumerable&lt; Wrapped_::ValueType &gt;',['../d3/dcc/structstingray_1_1IReversableEnumerable.html',1,'stingray']]],
  ['is1paramtemplate',['Is1ParamTemplate',['../dd/d97/structstingray_1_1Is1ParamTemplate.html',1,'stingray']]],
  ['is1paramtemplate_3c_20template_2c_20template_3c_20t_20_3e_20_3e',['Is1ParamTemplate&lt; Template, Template&lt; T &gt; &gt;',['../dc/d41/structstingray_1_1Is1ParamTemplate_3_01Template_00_01Template_3_01T_01_4_01_4.html',1,'stingray']]],
  ['is2paramtemplate',['Is2ParamTemplate',['../d1/df4/structstingray_1_1Is2ParamTemplate.html',1,'stingray']]],
  ['is2paramtemplate_3c_20template_2c_20template_3c_20t_2c_20u_20_3e_20_3e',['Is2ParamTemplate&lt; Template, Template&lt; T, U &gt; &gt;',['../dd/d1f/structstingray_1_1Is2ParamTemplate_3_01Template_00_01Template_3_01T_00_01U_01_4_01_4.html',1,'stingray']]],
  ['isanyof',['IsAnyOf',['../da/d98/classstingray_1_1IsAnyOf.html',1,'stingray']]],
  ['isarray',['IsArray',['../d2/db0/structstingray_1_1IsArray.html',1,'stingray']]],
  ['isarray_3c_20t_5bn_5d_3e',['IsArray&lt; T[N]&gt;',['../d3/d5b/structstingray_1_1IsArray_3_01T[N]_4.html',1,'stingray']]],
  ['isbuiltintype',['IsBuiltinType',['../d2/dc6/structstingray_1_1IsBuiltinType.html',1,'stingray']]],
  ['isclass',['IsClass',['../d0/d84/structstingray_1_1IsClass.html',1,'stingray']]],
  ['isclass_3c_20t_2c_20typename_20tovoid_3c_20int_20t_3a_3a_2a_20_3e_3a_3avaluet_20_3e',['IsClass&lt; T, typename ToVoid&lt; int T::* &gt;::ValueT &gt;',['../d0/d13/structstingray_1_1IsClass_3_01T_00_01typename_01ToVoid_3_01int_01T_1_1_5_01_4_1_1ValueT_01_4.html',1,'stingray']]],
  ['isconst',['IsConst',['../d5/dc7/structstingray_1_1IsConst.html',1,'stingray']]],
  ['isconst_3c_20const_20t_20_3e',['IsConst&lt; const T &gt;',['../d0/d41/structstingray_1_1IsConst_3_01const_01T_01_4.html',1,'stingray']]],
  ['isconstreference',['IsConstReference',['../dc/dc7/structstingray_1_1IsConstReference.html',1,'stingray']]],
  ['isconstreference_3c_20const_20t_20_26_20_3e',['IsConstReference&lt; const T &amp; &gt;',['../dd/d50/structstingray_1_1IsConstReference_3_01const_01T_01_6_01_4.html',1,'stingray']]],
  ['isenumclass',['IsEnumClass',['../d4/d2d/structstingray_1_1IsEnumClass.html',1,'stingray']]],
  ['isenumerable',['IsEnumerable',['../dd/d76/structstingray_1_1IsEnumerable.html',1,'stingray']]],
  ['isenumerator',['IsEnumerator',['../d4/d35/structstingray_1_1IsEnumerator.html',1,'stingray']]],
  ['iserializable',['ISerializable',['../d3/d72/structstingray_1_1ISerializable.html',1,'stingray']]],
  ['iset',['ISet',['../d5/d66/structstingray_1_1ISet.html',1,'stingray']]],
  ['iset_3c_20sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e_3a_3avaluetype_20_3e',['ISet&lt; SortedSet&lt; ValueType_, CompareType_ &gt;::ValueType &gt;',['../d5/d66/structstingray_1_1ISet.html',1,'stingray']]],
  ['iset_3c_20valuetype_5f_20_3e',['ISet&lt; ValueType_ &gt;',['../d5/d66/structstingray_1_1ISet.html',1,'stingray']]],
  ['iset_3c_20wrapped_5f_3a_3avaluetype_20_3e',['ISet&lt; Wrapped_::ValueType &gt;',['../d5/d66/structstingray_1_1ISet.html',1,'stingray']]],
  ['isettransaction',['ISetTransaction',['../d2/d90/structstingray_1_1ISetTransaction.html',1,'stingray']]],
  ['isfixedwidthinttype',['IsFixedWidthIntType',['../da/d3f/structstingray_1_1IsFixedWidthIntType.html',1,'stingray']]],
  ['isinttype',['IsIntType',['../dc/d31/structstingray_1_1IsIntType.html',1,'stingray']]],
  ['isnonconstreference',['IsNonConstReference',['../d4/d60/structstingray_1_1IsNonConstReference.html',1,'stingray']]],
  ['ispointer',['IsPointer',['../de/d6b/structstingray_1_1IsPointer.html',1,'stingray']]],
  ['ispointer_3c_20t_20_2a_20_3e',['IsPointer&lt; T * &gt;',['../d3/d03/structstingray_1_1IsPointer_3_01T_01_5_01_4.html',1,'stingray']]],
  ['ispointer_3c_20t_20_2aconst_20_20_3e',['IsPointer&lt; T *const  &gt;',['../d1/d42/structstingray_1_1IsPointer_3_01T_01_5const_01_01_4.html',1,'stingray']]],
  ['isrange',['IsRange',['../d0/d2c/structstingray_1_1IsRange.html',1,'stingray']]],
  ['isreference',['IsReference',['../d4/d7f/structstingray_1_1IsReference.html',1,'stingray']]],
  ['isreference_3c_20t_20_26_20_3e',['IsReference&lt; T &amp; &gt;',['../d2/db0/structstingray_1_1IsReference_3_01T_01_6_01_4.html',1,'stingray']]],
  ['issharedptr',['IsSharedPtr',['../dc/d1a/structstingray_1_1IsSharedPtr.html',1,'stingray']]],
  ['issharedptr_3c_20const_20shared_5fptr_3c_20t_20_3e_20_3e',['IsSharedPtr&lt; const shared_ptr&lt; T &gt; &gt;',['../d1/de9/structstingray_1_1IsSharedPtr_3_01const_01shared__ptr_3_01T_01_4_01_4.html',1,'stingray']]],
  ['issharedptr_3c_20shared_5fptr_3c_20t_20_3e_20_3e',['IsSharedPtr&lt; shared_ptr&lt; T &gt; &gt;',['../d6/d71/structstingray_1_1IsSharedPtr_3_01shared__ptr_3_01T_01_4_01_4.html',1,'stingray']]],
  ['issigned',['IsSigned',['../df/dc7/structstingray_1_1IsSigned.html',1,'stingray']]],
  ['issingleton',['IsSingleton',['../df/dd0/structstingray_1_1IsSingleton.html',1,'stingray']]],
  ['isstringrepresentable',['IsStringRepresentable',['../d0/d88/structstingray_1_1IsStringRepresentable.html',1,'stingray']]],
  ['isstringrepresentable',['IsStringRepresentable',['../d5/df9/structstingray_1_1SerializationUtils_1_1IsStringRepresentable.html',1,'stingray::SerializationUtils']]],
  ['istransformer',['IsTransformer',['../db/d5e/structstingray_1_1IsTransformer.html',1,'stingray']]],
  ['istringrepresentable',['IStringRepresentable',['../df/d31/structstingray_1_1IStringRepresentable.html',1,'stingray']]],
  ['itaskexecutor',['ITaskExecutor',['../d5/d31/structstingray_1_1ITaskExecutor.html',1,'stingray']]],
  ['iterator',['iterator',['../d5/d0e/classstingray_1_1IntrusiveList_1_1iterator.html',1,'stingray::IntrusiveList']]],
  ['iterator_5fbase',['iterator_base',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20bytedataiterator_3c_20t_20_3e_2c_20t_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_20_3e',['iterator_base&lt; ByteDataIterator&lt; T &gt;, T, std::random_access_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20const_5fiterator_2c_20const_20t_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['iterator_base&lt; const_iterator, const T, std::bidirectional_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20datajoineriterator_3c_20containerstypelist_20_3e_2c_20const_20u8_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_20_3e',['iterator_base&lt; DataJoinerIterator&lt; ContainersTypeList &gt;, const u8, std::random_access_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20enumiterator_3c_20enumclasst_20_3e_2c_20enumclasst_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_2c_20std_3a_3aptrdiff_5ft_2c_20const_20enumclasst_20_2a_2c_20const_20enumclasst_20_26_20_3e',['iterator_base&lt; EnumIterator&lt; EnumClassT &gt;, EnumClassT, std::random_access_iterator_tag, std::ptrdiff_t, const EnumClassT *, const EnumClassT &amp; &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20iterator_2c_20std_3a_3apair_3c_20const_20key_5f_20_26_2c_20value_5f_20_26_20_3e_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['iterator_base&lt; Iterator, std::pair&lt; const Key_ &amp;, Value_ &amp; &gt;, std::bidirectional_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20iterator_2c_20t_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['iterator_base&lt; iterator, T, std::bidirectional_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20mapkeysiterator_3c_20mapiterator_20_3e_2c_20detail_3a_3agetmapkeysiteratorpointedtype_3c_20mapiterator_20_3e_3a_3avaluet_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['iterator_base&lt; MapKeysIterator&lt; MapIterator &gt;, Detail::GetMapKeysIteratorPointedType&lt; MapIterator &gt;::ValueT, std::bidirectional_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20mapupdateiterator_3c_20map_20_3e_2c_20map_3a_3avalue_5ftype_2c_20std_3a_3aoutput_5fiterator_5ftag_2c_20map_3a_3adifference_5ftype_2c_20map_3a_3apointer_2c_20mapupdateiterator_3c_20map_20_3e_20_26_20_3e',['iterator_base&lt; MapUpdateIterator&lt; Map &gt;, Map::value_type, std::output_iterator_tag, Map::difference_type, Map::pointer, MapUpdateIterator&lt; Map &gt; &amp; &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20mapvaluesiterator_3c_20mapiterator_20_3e_2c_20detail_3a_3agetmapvaluesiteratorpointedtype_3c_20mapiterator_20_3e_3a_3avaluet_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['iterator_base&lt; MapValuesIterator&lt; MapIterator &gt;, Detail::GetMapValuesIteratorPointedType&lt; MapIterator &gt;::ValueT, std::bidirectional_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20observableiterator_3c_20t_2c_20container_20_3e_2c_20const_20t_2c_20std_3a_3arandom_5faccess_5fiterator_5ftag_20_3e',['iterator_base&lt; ObservableIterator&lt; T, Container &gt;, const T, std::random_access_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20skippingptriterator_3c_20rawiteratort_20_3e_2c_20detail_3a_3agetptrparam_3c_20rawiteratort_3a_3avalue_5ftype_20_3e_2c_20std_3a_3aforward_5fiterator_5ftag_20_3e',['iterator_base&lt; SkippingPtrIterator&lt; RawIteratorT &gt;, Detail::GetPtrParam&lt; RawIteratorT::value_type &gt;, std::forward_iterator_tag &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iterator_5fbase_3c_20weak_5flocker_5fiterator_3c_20wrappediterator_20_3e_2c_20shared_5fptr_3c_20getweakptrparam_3c_20std_3a_3aiterator_5ftraits_3c_20wrappediterator_20_3e_3a_3avalue_5ftype_20_3e_3a_3avaluet_20_3e_2c_20std_3a_3aforward_5fiterator_5ftag_2c_20std_3a_3aptrdiff_5ft_2c_20const_20shared_5fptr_3c_20getweakptrparam_3c_20std_3a_3aiterator_5ftraits_3c_20wrappediterator_20_3e_3a_3avalue_5ftype_20_3e_3a_3avaluet_20_3e_20_2a_2c_20const_20shared_5fptr_3c_20getweakptrparam_3c_20std_3a_3aiterator_5ftraits_3c_20wrappediterator_20_3e_3a_3avalue_5ftype_20_3e_3a_3avaluet_20_3e_20_26_20_3e',['iterator_base&lt; weak_locker_iterator&lt; WrappedIterator &gt;, shared_ptr&lt; GetWeakPtrParam&lt; std::iterator_traits&lt; WrappedIterator &gt;::value_type &gt;::ValueT &gt;, std::forward_iterator_tag, std::ptrdiff_t, const shared_ptr&lt; GetWeakPtrParam&lt; std::iterator_traits&lt; WrappedIterator &gt;::value_type &gt;::ValueT &gt; *, const shared_ptr&lt; GetWeakPtrParam&lt; std::iterator_traits&lt; WrappedIterator &gt;::value_type &gt;::ValueT &gt; &amp; &gt;',['../de/d7f/classstingray_1_1iterator__base.html',1,'stingray']]],
  ['iteratorrange',['IteratorRange',['../d3/d77/classstingray_1_1Range_1_1IteratorRange.html',1,'stingray::Range']]],
  ['iteratorsrangeenumerator',['IteratorsRangeEnumerator',['../df/d5b/classstingray_1_1IteratorsRangeEnumerator.html',1,'stingray']]],
  ['ithread',['IThread',['../db/dce/structstingray_1_1IThread.html',1,'stingray']]],
  ['ithreadinfo',['IThreadInfo',['../d3/deb/structstingray_1_1IThreadInfo.html',1,'stingray']]],
  ['itlsuserdata',['ITLSUserData',['../d7/deb/structstingray_1_1ITLSUserData.html',1,'stingray']]],
  ['itoken',['IToken',['../dd/dfe/structstingray_1_1IToken.html',1,'stingray']]],
  ['itransactionaldictionary',['ITransactionalDictionary',['../d9/d87/structstingray_1_1ITransactionalDictionary.html',1,'stingray']]],
  ['itransactionaldictionary_3c_20wrapped_5f_3a_3akeytype_2c_20wrapped_5f_3a_3avaluetype_20_3e',['ITransactionalDictionary&lt; Wrapped_::KeyType, Wrapped_::ValueType &gt;',['../d9/d87/structstingray_1_1ITransactionalDictionary.html',1,'stingray']]],
  ['itransactionalset',['ITransactionalSet',['../db/dcf/structstingray_1_1ITransactionalSet.html',1,'stingray']]],
  ['ivisitable',['IVisitable',['../d1/db7/structstingray_1_1IVisitable.html',1,'stingray']]],
  ['ivisitablebyptr',['IVisitableByPtr',['../d0/d67/structstingray_1_1IVisitableByPtr.html',1,'stingray']]],
  ['ivisitor',['IVisitor',['../d7/ddb/structstingray_1_1IVisitor.html',1,'stingray']]],
  ['ivisitor_3c_20basetype_2c_20void_20_3e',['IVisitor&lt; BaseType, void &gt;',['../dd/d03/structstingray_1_1IVisitor_3_01BaseType_00_01void_01_4.html',1,'stingray']]],
  ['ivisitorbyptr',['IVisitorByPtr',['../df/de7/classstingray_1_1IVisitorByPtr.html',1,'stingray']]],
  ['ivisitorbyptr_3c_20basetype_2c_20void_20_3e',['IVisitorByPtr&lt; BaseType, void &gt;',['../da/d4b/structstingray_1_1IVisitorByPtr_3_01BaseType_00_01void_01_4.html',1,'stingray']]]
];
