var searchData=
[
  ['accessdeniedexception',['AccessDeniedException',['../d9/d2f/structstingray_1_1AccessDeniedException.html',1,'stingray']]],
  ['accumulators',['Accumulators',['../d8/da1/structstingray_1_1Accumulators.html',1,'stingray']]],
  ['actionlogger',['ActionLogger',['../d8/d20/classstingray_1_1ActionLogger.html',1,'stingray']]],
  ['actiontransaction',['ActionTransaction',['../de/d58/classstingray_1_1ActionTransaction.html',1,'stingray']]],
  ['add',['Add',['../da/d6e/structstingray_1_1BasicAtomicInt.html#a8967737bac2b054e67ca856f3cd8fd0e',1,'stingray::BasicAtomicInt']]],
  ['added',['Added',['../d6/d07/structstingray_1_1CollectionOpVariant_1_1Added.html',1,'stingray::CollectionOpVariant']]],
  ['aggregateprogressreporter',['AggregateProgressReporter',['../dd/da4/classstingray_1_1AggregateProgressReporter.html',1,'stingray']]],
  ['aligned_5fstorage',['aligned_storage',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20maxsize_3a_3avalue_2c_20maxalignment_3a_3avalue_20_3e',['aligned_storage&lt; MaxSize::Value, MaxAlignment::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28dst_5f_29_2c_20stingray_3a_3aalignment_5fof_3c_20dst_5f_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(Dst_), stingray::alignment_of&lt; Dst_ &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28function_5fstorage_29_2c_20stingray_3a_3aalignment_5fof_3c_20function_5fstorage_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(function_storage), stingray::alignment_of&lt; function_storage &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28it_5f_29_2c_20stingray_3a_3aalignment_5fof_3c_20it_5f_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(It_), stingray::alignment_of&lt; It_ &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28namegetterfunc_29_2c_20stingray_3a_3aalignment_5fof_3c_20namegetterfunc_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(NameGetterFunc), stingray::alignment_of&lt; NameGetterFunc &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28pairtype_29_2c_20stingray_3a_3aalignment_5fof_3c_20pairtype_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(PairType), stingray::alignment_of&lt; PairType &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28std_3a_3astring_29_2c_20stingray_3a_3aalignment_5fof_3c_20std_3a_3astring_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(std::string), stingray::alignment_of&lt; std::string &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3abasicbytedata_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3abasicbytedata_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::BasicByteData), stingray::alignment_of&lt; stingray::BasicByteData &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3aelapsedtime_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3aelapsedtime_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::ElapsedTime), stingray::alignment_of&lt; stingray::ElapsedTime &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3aloglevel_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3aloglevel_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::LogLevel), stingray::alignment_of&lt; stingray::LogLevel &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3athreadschedulingparams_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3athreadschedulingparams_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::ThreadSchedulingParams), stingray::alignment_of&lt; stingray::ThreadSchedulingParams &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3atimeduration_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3atimeduration_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::TimeDuration), stingray::alignment_of&lt; stingray::TimeDuration &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28stingray_3a_3atoolkitwhere_29_2c_20stingray_3a_3aalignment_5fof_3c_20stingray_3a_3atoolkitwhere_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(stingray::ToolkitWhere), stingray::alignment_of&lt; stingray::ToolkitWhere &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28t_29_2c_20stingray_3a_3aalignment_5fof_3c_20t_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(T), stingray::alignment_of&lt; T &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28task_29_2c_20stingray_3a_3aalignment_5fof_3c_20task_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(Task), stingray::alignment_of&lt; Task &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28typename_20stingray_3a_3afunction_5finfo_3c_20functor_5f_20_3e_3a_3arettype_29_2c_20stingray_3a_3aalignment_5fof_3c_20typename_20stingray_3a_3afunction_5finfo_3c_20functor_5f_20_3e_3a_3arettype_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(typename stingray::function_info&lt; Functor_ &gt;::RetType), stingray::alignment_of&lt; typename stingray::function_info&lt; Functor_ &gt;::RetType &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['aligned_5fstorage_3c_20sizeof_28valuetype_29_2c_20stingray_3a_3aalignment_5fof_3c_20valuetype_20_3e_3a_3avalue_20_3e',['aligned_storage&lt; sizeof(ValueType), stingray::alignment_of&lt; ValueType &gt;::Value &gt;',['../d3/dc9/structstingray_1_1aligned__storage.html',1,'stingray']]],
  ['alignment_5fof',['alignment_of',['../db/d93/structstingray_1_1alignment__of.html',1,'stingray']]],
  ['allowdereferencing',['AllowDereferencing',['../de/dce/structstingray_1_1AllowDereferencing.html',1,'stingray']]],
  ['any',['any',['../de/db7/classstingray_1_1any.html',1,'stingray']]],
  ['anytransformer',['AnyTransformer',['../d6/d22/structstingray_1_1AnyTransformer.html',1,'stingray']]],
  ['anytransformerimpl',['AnyTransformerImpl',['../d6/dd8/structstingray_1_1AnyTransformerImpl.html',1,'stingray']]],
  ['anytransformerimpl_3c_20shared_5fptr_3c_20enumerable_5f_20_3e_2c_20typename_20enableif_3c_20isenumerable_3c_20enumerable_5f_20_3e_3a_3avalue_2c_20void_20_3e_3a_3avaluet_20_3e',['AnyTransformerImpl&lt; shared_ptr&lt; Enumerable_ &gt;, typename EnableIf&lt; IsEnumerable&lt; Enumerable_ &gt;::Value, void &gt;::ValueT &gt;',['../d8/d22/structstingray_1_1AnyTransformerImpl_3_01shared__ptr_3_01Enumerable___01_4_00_01typename_01Enabl77d3ab4d6c88b031fe562e89c9fe9bfc.html',1,'stingray']]],
  ['anytype',['AnyType',['../d5/d53/structstingray_1_1LangCode_1_1AnyType.html',1,'stingray::LangCode']]],
  ['argumentexception',['ArgumentException',['../d6/d0d/structstingray_1_1ArgumentException.html',1,'stingray']]],
  ['array',['array',['../d7/d2c/classstingray_1_1array.html',1,'stingray']]],
  ['array_3c_20char_2c_20size_20_3e',['array&lt; char, Size &gt;',['../d7/d2c/classstingray_1_1array.html',1,'stingray']]],
  ['array_3c_20stingray_3a_3astoragefor_3c_20t_20_3e_2c_20inplacecapacity_20_3e',['array&lt; stingray::StorageFor&lt; T &gt;, InplaceCapacity &gt;',['../d7/d2c/classstingray_1_1array.html',1,'stingray']]],
  ['array_3c_20u8_2c_2016_20_3e',['array&lt; u8, 16 &gt;',['../d7/d2c/classstingray_1_1array.html',1,'stingray']]],
  ['array_3c_20unsigned_2c_20maxframes_20_3e',['array&lt; unsigned, MaxFrames &gt;',['../d7/d2c/classstingray_1_1array.html',1,'stingray']]],
  ['arraylist',['ArrayList',['../dc/db5/classstingray_1_1ArrayList.html',1,'stingray']]],
  ['arraylist_3c_20valuetype_5f_20_3e',['ArrayList&lt; ValueType_ &gt;',['../dc/db5/classstingray_1_1ArrayList.html',1,'stingray']]],
  ['arrayobservablelist',['ArrayObservableList',['../d8/d9c/classstingray_1_1ArrayObservableList.html',1,'stingray']]],
  ['arrowproxy',['ArrowProxy',['../d9/dd1/structstingray_1_1Range_1_1ArrowProxy.html',1,'stingray::Range']]],
  ['asyncaction',['AsyncAction',['../da/d5d/classstingray_1_1AsyncAction.html',1,'stingray']]],
  ['asyncaction_3c_20statetype_2c_20void_20_3e',['AsyncAction&lt; StateType, void &gt;',['../da/dd8/classstingray_1_1AsyncAction_3_01StateType_00_01void_01_4.html',1,'stingray']]],
  ['asyncaction_3c_20void_2c_20void_20_3e',['AsyncAction&lt; void, void &gt;',['../d8/dc5/classstingray_1_1AsyncAction_3_01void_00_01void_01_4.html',1,'stingray']]],
  ['asyncfunction',['AsyncFunction',['../dd/dd8/classstingray_1_1AsyncFunction.html',1,'stingray']]],
  ['asyncprofiler',['AsyncProfiler',['../d0/d4c/classstingray_1_1AsyncProfiler.html',1,'stingray']]],
  ['asyncqueueprocessor',['AsyncQueueProcessor',['../db/d8c/classstingray_1_1AsyncQueueProcessor.html',1,'stingray']]],
  ['atomic',['atomic',['../df/d5f/classstingray_1_1atomic.html',1,'stingray']]],
  ['atomic_3c_20bool_20_3e',['atomic&lt; bool &gt;',['../df/d5f/classstingray_1_1atomic.html',1,'stingray']]],
  ['atomic_3c_20integertype_20_3e',['atomic&lt; IntegerType &gt;',['../df/d5f/classstingray_1_1atomic.html',1,'stingray']]],
  ['atomic_3c_20optionalloglevel_20_3e',['atomic&lt; OptionalLogLevel &gt;',['../df/d5f/classstingray_1_1atomic.html',1,'stingray']]],
  ['atomicflag',['AtomicFlag',['../d7/d03/structstingray_1_1AtomicFlag.html',1,'stingray']]],
  ['autocheckpointprofiler',['AutoCheckpointProfiler',['../d8/d75/classstingray_1_1AutoCheckpointProfiler.html',1,'stingray']]],
  ['average',['Average',['../d0/d6d/classstingray_1_1Average.html',1,'stingray']]]
];
