var searchData=
[
  ['random',['Random',['../d1/d16/classstingray_1_1Random.html',1,'stingray']]],
  ['rangebase',['RangeBase',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20enumerabletorange_3c_20enumerable_5f_20_3e_2c_20enumerable_5f_3a_3aitemtype_2c_20std_3a_3aforward_5fiterator_5ftag_20_3e',['RangeBase&lt; EnumerableToRange&lt; Enumerable_ &gt;, Enumerable_::ItemType, std::forward_iterator_tag &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20iteratorrange_3c_20it_5f_20_3e_2c_20std_3a_3aiterator_5ftraits_3c_20it_5f_20_3e_3a_3areference_2c_20std_3a_3aiterator_5ftraits_3c_20it_5f_20_3e_3a_3aiterator_5fcategory_20_3e',['RangeBase&lt; IteratorRange&lt; It_ &gt;, std::iterator_traits&lt; It_ &gt;::reference, std::iterator_traits&lt; It_ &gt;::iterator_category &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangecaster_3c_20dst_5f_2c_20range_5f_20_3e_2c_20dst_5f_2c_20range_5f_3a_3acategory_20_3e',['RangeBase&lt; RangeCaster&lt; Dst_, Range_ &gt;, Dst_, Range_::Category &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangecycler_3c_20range_5f_20_3e_2c_20range_5f_3a_3avaluetype_2c_20rangefiltercategoryhelper_3c_20range_5f_3a_3acategory_20_3e_3a_3avaluet_20_3e',['RangeBase&lt; RangeCycler&lt; Range_ &gt;, Range_::ValueType, RangeFilterCategoryHelper&lt; Range_::Category &gt;::ValueT &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangefilter_3c_20range_5f_2c_20predicate_5f_20_3e_2c_20range_5f_3a_3avaluetype_2c_20rangefiltercategoryhelper_3c_20range_5f_3a_3acategory_20_3e_3a_3avaluet_20_3e',['RangeBase&lt; RangeFilter&lt; Range_, Predicate_ &gt;, Range_::ValueType, RangeFilterCategoryHelper&lt; Range_::Category &gt;::ValueT &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangeoftype_3c_20dst_5f_2c_20range_5f_20_3e_2c_20dst_5f_2c_20rangefiltercategoryhelper_3c_20range_5f_3a_3acategory_20_3e_3a_3avaluet_20_3e',['RangeBase&lt; RangeOfType&lt; Dst_, Range_ &gt;, Dst_, RangeFilterCategoryHelper&lt; Range_::Category &gt;::ValueT &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangereverser_3c_20range_5f_20_3e_2c_20range_5f_3a_3avaluetype_2c_20range_5f_3a_3acategory_20_3e',['RangeBase&lt; RangeReverser&lt; Range_ &gt;, Range_::ValueType, Range_::Category &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20rangetransformer_3c_20range_5f_2c_20functor_5f_20_3e_2c_20getconstreferencetype_3c_20function_5finfo_3c_20functor_5f_20_3e_3a_3arettype_20_3e_3a_3avaluet_2c_20range_5f_3a_3acategory_20_3e',['RangeBase&lt; RangeTransformer&lt; Range_, Functor_ &gt;, GetConstReferenceType&lt; function_info&lt; Functor_ &gt;::RetType &gt;::ValueT, Range_::Category &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20splitstringrange_3c_20stringsearchtype_20_3e_2c_20stringref_2c_20std_3a_3aforward_5fiterator_5ftag_20_3e',['RangeBase&lt; SplitStringRange&lt; StringSearchType &gt;, StringRef, std::forward_iterator_tag &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangebase_3c_20utf8iteratorrange_3c_20containertype_20_3e_2c_20u32_2c_20std_3a_3abidirectional_5fiterator_5ftag_20_3e',['RangeBase&lt; Utf8IteratorRange&lt; ContainerType &gt;, u32, std::bidirectional_iterator_tag &gt;',['../d3/d40/structstingray_1_1Range_1_1RangeBase.html',1,'stingray::Range']]],
  ['rangecaster',['RangeCaster',['../d2/d5e/classstingray_1_1Range_1_1RangeCaster.html',1,'stingray::Range']]],
  ['rangecycler',['RangeCycler',['../d2/d50/classstingray_1_1Range_1_1RangeCycler.html',1,'stingray::Range']]],
  ['rangefilter',['RangeFilter',['../d1/db6/classstingray_1_1Range_1_1RangeFilter.html',1,'stingray::Range']]],
  ['rangefiltercategoryhelper',['RangeFilterCategoryHelper',['../d3/d9f/structstingray_1_1Range_1_1RangeFilterCategoryHelper.html',1,'stingray::Range']]],
  ['rangefiltercategoryhelper_3c_20std_3a_3arandom_5faccess_5fiterator_5ftag_20_3e',['RangeFilterCategoryHelper&lt; std::random_access_iterator_tag &gt;',['../d1/d8a/structstingray_1_1Range_1_1RangeFilterCategoryHelper_3_01std_1_1random__access__iterator__tag_01_4.html',1,'stingray::Range']]],
  ['rangemarker',['RangeMarker',['../d6/dab/structstingray_1_1RangeMarker.html',1,'stingray']]],
  ['rangeoftype',['RangeOfType',['../d8/dec/classstingray_1_1Range_1_1RangeOfType.html',1,'stingray::Range']]],
  ['rangereverser',['RangeReverser',['../d9/dd8/classstingray_1_1Range_1_1RangeReverser.html',1,'stingray::Range']]],
  ['rangetransformer',['RangeTransformer',['../d4/d7c/classstingray_1_1Range_1_1RangeTransformer.html',1,'stingray::Range']]],
  ['rational',['Rational',['../d2/df6/structstingray_1_1Rational.html',1,'stingray']]],
  ['reactivedatasource',['ReactiveDataSource',['../d1/d30/classstingray_1_1ReactiveDataSource.html',1,'stingray']]],
  ['reader',['Reader',['../d2/d46/structstingray_1_1BithreadCircularBuffer_1_1Reader.html',1,'stingray::BithreadCircularBuffer']]],
  ['readline',['ReadLine',['../d1/de8/classstingray_1_1PipeReader.html#a57e974a4ba7d824d88bbc73c1018c098',1,'stingray::PipeReader']]],
  ['refcountingmap',['RefCountingMap',['../d8/ded/classstingray_1_1RefCountingMap.html',1,'stingray']]],
  ['reference',['reference',['../d9/d53/classstingray_1_1reference.html',1,'stingray']]],
  ['refstorage',['RefStorage',['../d0/dcb/structstingray_1_1RefStorage.html',1,'stingray']]],
  ['refstorage_3c_20t_20_26_20_3e',['RefStorage&lt; T &amp; &gt;',['../d9/dac/structstingray_1_1RefStorage_3_01T_01_6_01_4.html',1,'stingray']]],
  ['regex',['regex',['../de/d4a/classstingray_1_1regex.html',1,'stingray']]],
  ['regex_5ferror',['regex_error',['../df/d18/structstingray_1_1regex__error.html',1,'stingray']]],
  ['registryentry',['RegistryEntry',['../d4/dec/structstingray_1_1GenericInvoker_1_1RegistryEntry.html',1,'stingray::GenericInvoker']]],
  ['registryentry',['RegistryEntry',['../d2/dd4/structstingray_1_1GenericEntityFactory_1_1RegistryEntry.html',1,'stingray::GenericEntityFactory']]],
  ['removed',['Removed',['../da/da5/structstingray_1_1CollectionOpVariant_1_1Removed.html',1,'stingray::CollectionOpVariant']]],
  ['removeextent',['RemoveExtent',['../db/dc8/structstingray_1_1RemoveExtent.html',1,'stingray']]],
  ['removeextent_3c_20t_5b_5d_3e',['RemoveExtent&lt; T[]&gt;',['../db/dc9/structstingray_1_1RemoveExtent_3_01T[]_4.html',1,'stingray']]],
  ['removeextent_3c_20t_5bn_5d_3e',['RemoveExtent&lt; T[N]&gt;',['../d3/da6/structstingray_1_1RemoveExtent_3_01T[N]_4.html',1,'stingray']]],
  ['result',['Result',['../da/d76/structstingray_1_1CheckpointProfiler_1_1Result.html',1,'stingray::CheckpointProfiler']]],
  ['rethrown_5fexception',['rethrown_exception',['../dc/d48/classstingray_1_1rethrown__exception.html',1,'stingray']]],
  ['rettype',['RetType',['../d5/df4/structstingray_1_1function__info.html#a5f8dfed848e9a7be8522355945ed7dd1',1,'stingray::function_info']]],
  ['reversetransformer',['ReverseTransformer',['../dd/db1/structstingray_1_1ReverseTransformer.html',1,'stingray']]],
  ['reversetransformerimpl',['ReverseTransformerImpl',['../d2/dc3/structstingray_1_1ReverseTransformerImpl.html',1,'stingray']]],
  ['reversetransformerimpl_3c_20range_5f_2c_20typename_20enableif_3c_20isrange_3c_20range_5f_20_3e_3a_3avalue_2c_20void_20_3e_3a_3avaluet_20_3e',['ReverseTransformerImpl&lt; Range_, typename EnableIf&lt; IsRange&lt; Range_ &gt;::Value, void &gt;::ValueT &gt;',['../da/d0b/structstingray_1_1ReverseTransformerImpl_3_01Range___00_01typename_01EnableIf_3_01IsRange_3_01Ra4a7f9e057ed9647659ffd208b4e896d2.html',1,'stingray']]],
  ['reversetransformerimpl_3c_20shared_5fptr_3c_20enumerable_5f_20_3e_2c_20typename_20enableif_3c_20isenumerable_3c_20enumerable_5f_20_3e_3a_3avalue_2c_20void_20_3e_3a_3avaluet_20_3e',['ReverseTransformerImpl&lt; shared_ptr&lt; Enumerable_ &gt;, typename EnableIf&lt; IsEnumerable&lt; Enumerable_ &gt;::Value, void &gt;::ValueT &gt;',['../dd/d45/structstingray_1_1ReverseTransformerImpl_3_01shared__ptr_3_01Enumerable___01_4_00_01typename_01E9a48e6b9f88bbefe5928cc9774087b2f.html',1,'stingray']]],
  ['rollback',['Rollback',['../d3/dc0/classstingray_1_1BasicBitStream_1_1Rollback.html',1,'stingray::BasicBitStream']]]
];
