var searchData=
[
  ['safe_5fbool',['safe_bool',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20derived_5f_20_3e',['safe_bool&lt; Derived_ &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20enumerabletorange_3c_20enumerable_5f_20_3e_20_3e',['safe_bool&lt; EnumerableToRange&lt; Enumerable_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20icancellationtoken_20_3e',['safe_bool&lt; ICancellationToken &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20iteratorrange_3c_20it_5f_20_3e_20_3e',['safe_bool&lt; IteratorRange&lt; It_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20light_5fshared_5fptr_3c_20t_20_3e_20_3e',['safe_bool&lt; light_shared_ptr&lt; T &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20localexecutionguard_20_3e',['safe_bool&lt; LocalExecutionGuard &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20dst_5f_20_3e_20_3e',['safe_bool&lt; optional&lt; Dst_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20function_5fstorage_20_3e_20_3e',['safe_bool&lt; optional&lt; function_storage &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20it_5f_20_3e_20_3e',['safe_bool&lt; optional&lt; It_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20namegetterfunc_20_3e_20_3e',['safe_bool&lt; optional&lt; NameGetterFunc &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20pairtype_20_3e_20_3e',['safe_bool&lt; optional&lt; PairType &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20std_3a_3astring_20_3e_20_3e',['safe_bool&lt; optional&lt; std::string &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3abasicbytedata_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::BasicByteData &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3aelapsedtime_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::ElapsedTime &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3aloglevel_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::LogLevel &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3athreadschedulingparams_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::ThreadSchedulingParams &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3atimeduration_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::TimeDuration &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20stingray_3a_3atoolkitwhere_20_3e_20_3e',['safe_bool&lt; optional&lt; stingray::ToolkitWhere &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20t_20_3e_20_3e',['safe_bool&lt; optional&lt; T &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20task_20_3e_20_3e',['safe_bool&lt; optional&lt; Task &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20typename_20stingray_3a_3afunction_5finfo_3c_20functor_5f_20_3e_3a_3arettype_20_3e_20_3e',['safe_bool&lt; optional&lt; typename stingray::function_info&lt; Functor_ &gt;::RetType &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20optional_3c_20valuetype_20_3e_20_3e',['safe_bool&lt; optional&lt; ValueType &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangecaster_3c_20dst_5f_2c_20range_5f_20_3e_20_3e',['safe_bool&lt; RangeCaster&lt; Dst_, Range_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangecycler_3c_20range_5f_20_3e_20_3e',['safe_bool&lt; RangeCycler&lt; Range_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangefilter_3c_20range_5f_2c_20predicate_5f_20_3e_20_3e',['safe_bool&lt; RangeFilter&lt; Range_, Predicate_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangeoftype_3c_20dst_5f_2c_20range_5f_20_3e_20_3e',['safe_bool&lt; RangeOfType&lt; Dst_, Range_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangereverser_3c_20range_5f_20_3e_20_3e',['safe_bool&lt; RangeReverser&lt; Range_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20rangetransformer_3c_20range_5f_2c_20functor_5f_20_3e_20_3e',['safe_bool&lt; RangeTransformer&lt; Range_, Functor_ &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20self_5fcount_5fptr_3c_20detail_3a_3aisignalconnector_20_3e_20_3e',['safe_bool&lt; self_count_ptr&lt; Detail::ISignalConnector &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20self_5fcount_5fptr_3c_20stingray_3a_3aitoken_20_3e_20_3e',['safe_bool&lt; self_count_ptr&lt; stingray::IToken &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20self_5fcount_5fptr_3c_20t_20_3e_20_3e',['safe_bool&lt; self_count_ptr&lt; T &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20shared_5fptr_3c_20t_20_3e_20_3e',['safe_bool&lt; shared_ptr&lt; T &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20splitstringrange_3c_20stringsearchtype_20_3e_20_3e',['safe_bool&lt; SplitStringRange&lt; StringSearchType &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20token_20_3e',['safe_bool&lt; Token &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20unique_5fptr_3c_20t_20_3e_20_3e',['safe_bool&lt; unique_ptr&lt; T &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safe_5fbool_3c_20utf8iteratorrange_3c_20containertype_20_3e_20_3e',['safe_bool&lt; Utf8IteratorRange&lt; ContainerType &gt; &gt;',['../d4/dc0/classstingray_1_1safe__bool.html',1,'stingray']]],
  ['safesingleton',['SafeSingleton',['../d6/d33/classstingray_1_1SafeSingleton.html',1,'stingray']]],
  ['sametype',['SameType',['../d3/d9e/structstingray_1_1SameType.html',1,'stingray']]],
  ['sametype_3c_20t_2c_20t_20_3e',['SameType&lt; T, T &gt;',['../dc/d6e/structstingray_1_1SameType_3_01T_00_01T_01_4.html',1,'stingray']]],
  ['scopedholder',['ScopedHolder',['../d5/dca/classstingray_1_1ScopedHolder.html',1,'stingray']]],
  ['scopedholder_3c_20void_20_3e',['ScopedHolder&lt; void &gt;',['../d1/de2/classstingray_1_1ScopedHolder_3_01void_01_4.html',1,'stingray']]],
  ['scopeexitinvoker',['ScopeExitInvoker',['../d8/df7/classstingray_1_1ScopeExitInvoker.html',1,'stingray']]],
  ['seekmode',['SeekMode',['../dd/dda/structstingray_1_1SeekMode.html',1,'stingray']]],
  ['selectmode',['SelectMode',['../d4/dac/structstingray_1_1SelectMode.html',1,'stingray']]],
  ['self_5fcount_5fless',['self_count_less',['../db/dc2/structstingray_1_1self__count__less.html',1,'stingray']]],
  ['self_5fcount_5fless_3c_20self_5fcount_5fptr_3c_20t_20_3e_20_3e',['self_count_less&lt; self_count_ptr&lt; T &gt; &gt;',['../d3/df5/structstingray_1_1self__count__less_3_01self__count__ptr_3_01T_01_4_01_4.html',1,'stingray']]],
  ['self_5fcount_5fptr',['self_count_ptr',['../da/dbb/classstingray_1_1self__count__ptr.html',1,'stingray']]],
  ['self_5fcount_5fptr_3c_20detail_3a_3aisignalconnector_20_3e',['self_count_ptr&lt; Detail::ISignalConnector &gt;',['../da/dbb/classstingray_1_1self__count__ptr.html',1,'stingray']]],
  ['self_5fcount_5fptr_3c_20stingray_3a_3aitoken_20_3e',['self_count_ptr&lt; stingray::IToken &gt;',['../da/dbb/classstingray_1_1self__count__ptr.html',1,'stingray']]],
  ['self_5fcounter',['self_counter',['../d5/d4e/classstingray_1_1self__counter.html',1,'stingray']]],
  ['self_5fcounter_3c_20isignalconnector_20_3e',['self_counter&lt; ISignalConnector &gt;',['../d5/d4e/classstingray_1_1self__counter.html',1,'stingray']]],
  ['self_5fcounter_3c_20itoken_20_3e',['self_counter&lt; IToken &gt;',['../d5/d4e/classstingray_1_1self__counter.html',1,'stingray']]],
  ['self_5fcounter_3c_20settingsvalue_20_3e',['self_counter&lt; SettingsValue &gt;',['../d5/d4e/classstingray_1_1self__counter.html',1,'stingray']]],
  ['self_5fcounter_3c_20tasklifetokenimpl_20_3e',['self_counter&lt; TaskLifeTokenImpl &gt;',['../d5/d4e/classstingray_1_1self__counter.html',1,'stingray']]],
  ['serializationutils',['SerializationUtils',['../dc/de1/structstingray_1_1SerializationUtils.html',1,'stingray']]],
  ['session',['Session',['../d3/d8a/classstingray_1_1AsyncProfiler_1_1Session.html',1,'stingray::AsyncProfiler']]],
  ['settingsvalue',['SettingsValue',['../da/d03/classstingray_1_1SettingsValue.html',1,'stingray']]],
  ['settingsvalueexception',['SettingsValueException',['../d0/d99/classstingray_1_1SettingsValueException.html',1,'stingray']]],
  ['shared_5fcopy_5fback_5finsert_5fiterator',['shared_copy_back_insert_iterator',['../d6/d24/structstingray_1_1shared__copy__back__insert__iterator.html',1,'stingray']]],
  ['shared_5ffuture',['shared_future',['../d8/de8/classstingray_1_1shared__future.html',1,'stingray']]],
  ['shared_5ffuture_3c_20paramtype_20_3e',['shared_future&lt; ParamType &gt;',['../d8/de8/classstingray_1_1shared__future.html',1,'stingray']]],
  ['shared_5ffuture_3c_20void_20_3e',['shared_future&lt; void &gt;',['../d8/de8/classstingray_1_1shared__future.html',1,'stingray']]],
  ['shared_5fptr',['shared_ptr',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20asyncprofiler_20_3e',['shared_ptr&lt; AsyncProfiler &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20builder_20_3e',['shared_ptr&lt; Builder &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20callbackqueue_20_3e',['shared_ptr&lt; CallbackQueue &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20checkpointprofilerholder_20_3e',['shared_ptr&lt; CheckpointProfilerHolder &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20collectiontype_20_3e',['shared_ptr&lt; CollectionType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20container_20_3e',['shared_ptr&lt; Container &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20containerlifeassurancetype_20_3e',['shared_ptr&lt; ContainerLifeAssuranceType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20containertype_20_3e',['shared_ptr&lt; ContainerType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20detail_3a_3afuture_5fimpl_3c_20paramtype_20_3e_20_3e',['shared_ptr&lt; Detail::future_impl&lt; ParamType &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20detail_3a_3afuture_5fimpl_3c_20resulttype_20_3e_20_3e',['shared_ptr&lt; Detail::future_impl&lt; ResultType &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20detail_3a_3afuture_5fimpl_3c_20void_20_3e_20_3e',['shared_ptr&lt; Detail::future_impl&lt; void &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20detail_3a_3ahideduplicatinglogs_20_3e',['shared_ptr&lt; Detail::HideDuplicatingLogs &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20dictionary_20_3e',['shared_ptr&lt; Dictionary &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20dictionarytype_20_3e',['shared_ptr&lt; DictionaryType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20eventwatcher_20_3e',['shared_ptr&lt; EventWatcher &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20executiondeferrer_20_3e',['shared_ptr&lt; ExecutionDeferrer &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20executiondeferrerwithtimer_20_3e',['shared_ptr&lt; ExecutionDeferrerWithTimer &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20factorycontext_20_3e',['shared_ptr&lt; FactoryContext &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20futureimpltype_20_3e',['shared_ptr&lt; FutureImplType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20holder_20_3e',['shared_ptr&lt; Holder &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ibytestream_20_3e',['shared_ptr&lt; IByteStream &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20idatabuffer_20_3e',['shared_ptr&lt; IDataBuffer &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20idatasource_20_3e',['shared_ptr&lt; IDataSource &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ienumerable_3c_20enumeratedt_20_3e_20_3e',['shared_ptr&lt; IEnumerable&lt; EnumeratedT &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ienumerable_3c_20srctype_20_3e_20_3e',['shared_ptr&lt; IEnumerable&lt; SrcType &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ienumerator_3c_20enumeratedt_20_3e_20_3e',['shared_ptr&lt; IEnumerator&lt; EnumeratedT &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ienumerator_3c_20srctype_20_3e_20_3e',['shared_ptr&lt; IEnumerator&lt; SrcType &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ienumerator_3c_20stingray_3a_3adetail_3a_3agetitemtypefromitemdecl_3c_20itemdeclfunc_20_3e_3a_3avaluet_20_3e_20_3e',['shared_ptr&lt; IEnumerator&lt; stingray::Detail::GetItemTypeFromItemDecl&lt; ItemDeclFunc &gt;::ValueT &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20impl_20_3e',['shared_ptr&lt; Impl &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20impltype_20_3e',['shared_ptr&lt; ImplType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ipipe_20_3e',['shared_ptr&lt; IPipe &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20itaskexecutor_20_3e',['shared_ptr&lt; ITaskExecutor &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ithread_20_3e',['shared_ptr&lt; IThread &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20ithreadinfo_20_3e',['shared_ptr&lt; IThreadInfo &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20itimerconnectionimpl_20_3e',['shared_ptr&lt; ITimerConnectionImpl &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20itlsuserdata_20_3e',['shared_ptr&lt; ITLSUserData &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20maptype_20_3e',['shared_ptr&lt; MapType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20packetsource_20_3e',['shared_ptr&lt; PacketSource &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20promise_20_3e',['shared_ptr&lt; Promise &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20promiseref_20_3e',['shared_ptr&lt; PromiseRef &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20setimpl_20_3e',['shared_ptr&lt; SetImpl &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20settype_20_3e',['shared_ptr&lt; SetType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20stingray_3a_3abasic_5fstring_5fostream_20_3e',['shared_ptr&lt; stingray::basic_string_ostream &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20stingray_3a_3aienumerator_3c_20t_20_3e_20_3e',['shared_ptr&lt; stingray::IEnumerator&lt; T &gt; &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20stingray_3a_3aposixmutex_20_3e',['shared_ptr&lt; stingray::PosixMutex &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20thread_20_3e',['shared_ptr&lt; Thread &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20threaddatastorage_20_3e',['shared_ptr&lt; ThreadDataStorage &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20threadsregistry_20_3e',['shared_ptr&lt; ThreadsRegistry &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20tptr_20_3e',['shared_ptr&lt; TPtr &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20typename_20base_3a_3avalue_5ftype_20_3e',['shared_ptr&lt; typename base::value_type &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20vectortype_20_3e',['shared_ptr&lt; VectorType &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_3c_20wrapped_5f_20_3e',['shared_ptr&lt; Wrapped_ &gt;',['../d2/d13/classstingray_1_1shared__ptr.html',1,'stingray']]],
  ['shared_5fptr_5ftraits',['shared_ptr_traits',['../da/dc1/structstingray_1_1shared__ptr__traits.html',1,'stingray']]],
  ['sharedholder',['SharedHolder',['../df/d28/classstingray_1_1SharedHolder.html',1,'stingray']]],
  ['sharedholder_3c_20void_20_3e',['SharedHolder&lt; void &gt;',['../df/d70/classstingray_1_1SharedHolder_3_01void_01_4.html',1,'stingray']]],
  ['shorthexdumpformatter',['ShortHexDumpFormatter',['../d6/d2e/structstingray_1_1ShortHexDumpFormatter.html',1,'stingray']]],
  ['signal',['signal',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28_29_3e',['signal&lt; void()&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28bool_29_3e',['signal&lt; void(bool)&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28const_20stingray_3a_3ashared_5fptr_20_26_29_2c_20signal_5fpolicies_3a_3athreading_3a_3aexternalmutexpointer_20_3e',['signal&lt; void(const stingray::shared_ptr &amp;), signal_policies::threading::ExternalMutexPointer &gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28parampassingtype_29_3e',['signal&lt; void(ParamPassingType)&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28size_5ft_29_3e',['signal&lt; void(size_t)&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3acollectionop_2c_20const_20valuetype_20_26_29_2c_20signal_5fpolicies_3a_3athreading_3a_3aexternalmutex_20_3e',['signal&lt; void(stingray::CollectionOp, const ValueType &amp;), signal_policies::threading::ExternalMutex &gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3acollectionop_2c_20const_20valuetype_5f_20_26_29_2c_20stingray_3a_3asignal_5fpolicies_3a_3athreading_3a_3aexternalmutexpointer_20_3e',['signal&lt; void(stingray::CollectionOp, const ValueType_ &amp;), stingray::signal_policies::threading::ExternalMutexPointer &gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3acollectionop_2c_20int_2c_20const_20valuetype_20_26_29_2c_20signal_5fpolicies_3a_3athreading_3a_3aexternalmutexpointer_20_3e',['signal&lt; void(stingray::CollectionOp, int, const ValueType &amp;), signal_policies::threading::ExternalMutexPointer &gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3acollectionop_2c_20keytype_2c_20valuetype_29_2c_20stingray_3a_3asignal_5fpolicies_3a_3athreading_3a_3aexternalmutexpointer_20_3e',['signal&lt; void(stingray::CollectionOp, KeyType, ValueType), stingray::signal_policies::threading::ExternalMutexPointer &gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3acollectionop_2c_20size_5ft_2c_20const_20t_20_26_29_3e',['signal&lt; void(stingray::CollectionOp, size_t, const T &amp;)&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_3c_20void_28stingray_3a_3aprogressvalue_29_3e',['signal&lt; void(stingray::ProgressValue)&gt;',['../d6/d76/structstingray_1_1signal.html',1,'stingray']]],
  ['signal_5fconnector',['signal_connector',['../dc/dac/classstingray_1_1signal__connector.html',1,'stingray']]],
  ['signalhandlersetter',['SignalHandlerSetter',['../d9/d88/classstingray_1_1posix_1_1SignalHandlerSetter.html',1,'stingray::posix']]],
  ['signaltofuturewrapper',['SignalToFutureWrapper',['../d6/d22/classstingray_1_1SignalToFutureWrapper.html',1,'stingray']]],
  ['signaltofuturewrapper_3c_20void_20_3e',['SignalToFutureWrapper&lt; void &gt;',['../d9/d7d/classstingray_1_1SignalToFutureWrapper_3_01void_01_4.html',1,'stingray']]],
  ['simpleenumerable',['SimpleEnumerable',['../df/de7/classstingray_1_1SimpleEnumerable.html',1,'stingray']]],
  ['simplenumericrange',['SimpleNumericRange',['../db/dca/structstingray_1_1SimpleNumericRange.html',1,'stingray']]],
  ['singleinstancecreator',['SingleInstanceCreator',['../d2/d30/structstingray_1_1SingleInstanceCreator.html',1,'stingray']]],
  ['singleinstancecreatorbase',['SingleInstanceCreatorBase',['../d4/d72/structstingray_1_1SingleInstanceCreatorBase.html',1,'stingray']]],
  ['singleton',['Singleton',['../d4/d84/classstingray_1_1Singleton.html',1,'stingray']]],
  ['singleton_3c_20factory_20_3e',['Singleton&lt; Factory &gt;',['../d4/d84/classstingray_1_1Singleton.html',1,'stingray']]],
  ['singleton_3c_20posixconditionvariableattr_20_3e',['Singleton&lt; PosixConditionVariableAttr &gt;',['../d4/d84/classstingray_1_1Singleton.html',1,'stingray']]],
  ['singleton_3c_20posixmutexattr_20_3e',['Singleton&lt; PosixMutexAttr &gt;',['../d4/d84/classstingray_1_1Singleton.html',1,'stingray']]],
  ['size',['Size',['../d3/dbc/structstingray_1_1Size.html',1,'stingray']]],
  ['sizeof',['SizeOf',['../d2/d7c/structstingray_1_1SizeOf.html',1,'stingray']]],
  ['skippingptriterator',['SkippingPtrIterator',['../dd/d6d/structstingray_1_1SkippingPtrIterator.html',1,'stingray']]],
  ['smatch',['smatch',['../d1/dd5/classstingray_1_1smatch.html',1,'stingray']]],
  ['socketexception',['SocketException',['../d1/d22/structstingray_1_1SocketException.html',1,'stingray']]],
  ['sortedobservableset',['SortedObservableSet',['../df/d58/classstingray_1_1SortedObservableSet.html',1,'stingray']]],
  ['sortedset',['SortedSet',['../d5/d73/classstingray_1_1SortedSet.html',1,'stingray']]],
  ['sortedset_3c_20valuetype_5f_2c_20comparetype_5f_20_3e',['SortedSet&lt; ValueType_, CompareType_ &gt;',['../d5/d73/classstingray_1_1SortedSet.html',1,'stingray']]],
  ['spinlock',['Spinlock',['../d9/dd4/classstingray_1_1Spinlock.html',1,'stingray']]],
  ['srcfit',['SrcFit',['../d8/d43/structstingray_1_1TypeMapper_1_1Map_1_1SrcFit.html',1,'stingray::TypeMapper::Map']]],
  ['stackentry',['StackEntry',['../db/dcf/structstingray_1_1ExternalAPIGuardStack_1_1StackEntry.html',1,'stingray::ExternalAPIGuardStack']]],
  ['stat',['Stat',['../d6/dd5/structstingray_1_1Stat.html',1,'stingray']]],
  ['static_5fcast_5ftag',['static_cast_tag',['../da/d9d/structstingray_1_1static__cast__tag.html',1,'stingray']]],
  ['static_5fvisitor',['static_visitor',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20bool_20_3e',['static_visitor&lt; bool &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20const_20std_3a_3atype_5finfo_20_2a_20_3e',['static_visitor&lt; const std::type_info * &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20desiredtype_20_2a_20_3e',['static_visitor&lt; DesiredType * &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20multivisitor_5f_3a_3arettype_20_3e',['static_visitor&lt; Multivisitor_::RetType &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20pointer_20_3e',['static_visitor&lt; pointer &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20rettype_5f_20_3e',['static_visitor&lt; RetType_ &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20std_3a_3astring_20_3e',['static_visitor&lt; std::string &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20visitor_3a_3arettype_20_3e',['static_visitor&lt; Visitor::RetType &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_20void_20_3e',['static_visitor&lt; void &gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['static_5fvisitor_3c_3e',['static_visitor&lt;&gt;',['../de/dd1/structstingray_1_1static__visitor.html',1,'stingray']]],
  ['staticassertcompletetype',['StaticAssertCompleteType',['../d0/dc4/structstingray_1_1StaticAssertCompleteType.html',1,'stingray']]],
  ['stlenumeratoradapter',['StlEnumeratorAdapter',['../d5/d0f/classstingray_1_1StlEnumeratorAdapter.html',1,'stingray']]],
  ['storagefor',['StorageFor',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20dst_5f_20_3e',['StorageFor&lt; Dst_ &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20function_5fstorage_20_3e',['StorageFor&lt; function_storage &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20it_5f_20_3e',['StorageFor&lt; It_ &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20namegetterfunc_20_3e',['StorageFor&lt; NameGetterFunc &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20pairtype_20_3e',['StorageFor&lt; PairType &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20std_3a_3astring_20_3e',['StorageFor&lt; std::string &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3abasicbytedata_20_3e',['StorageFor&lt; stingray::BasicByteData &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3aelapsedtime_20_3e',['StorageFor&lt; stingray::ElapsedTime &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3aloglevel_20_3e',['StorageFor&lt; stingray::LogLevel &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3athreadschedulingparams_20_3e',['StorageFor&lt; stingray::ThreadSchedulingParams &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3atimeduration_20_3e',['StorageFor&lt; stingray::TimeDuration &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20stingray_3a_3atoolkitwhere_20_3e',['StorageFor&lt; stingray::ToolkitWhere &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20task_20_3e',['StorageFor&lt; Task &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20typename_20stingray_3a_3afunction_5finfo_3c_20functor_5f_20_3e_3a_3arettype_20_3e',['StorageFor&lt; typename stingray::function_info&lt; Functor_ &gt;::RetType &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['storagefor_3c_20valuetype_20_3e',['StorageFor&lt; ValueType &gt;',['../d3/dba/structstingray_1_1StorageFor.html',1,'stingray']]],
  ['stringcodec',['StringCodec',['../d8/d68/structstingray_1_1StringCodec.html',1,'stingray']]],
  ['stringcounter',['StringCounter',['../d5/d37/structstingray_1_1DuplicatingLogsFilter_1_1StringCounter.html',1,'stingray::DuplicatingLogsFilter']]],
  ['stringreader',['StringReader',['../d6/d95/classstingray_1_1StringReader.html',1,'stingray']]],
  ['stringtochararrayhelper',['StringToCharArrayHelper',['../de/de3/structstingray_1_1StringToCharArrayHelper.html',1,'stingray']]],
  ['systemexception',['SystemException',['../d5/d94/structstingray_1_1SystemException.html',1,'stingray']]],
  ['systemlogger',['SystemLogger',['../d8/d3b/structstingray_1_1SystemLogger.html',1,'stingray']]],
  ['systemprofiler',['SystemProfiler',['../df/de6/classstingray_1_1SystemProfiler.html',1,'stingray']]],
  ['systemstats',['SystemStats',['../d3/d8c/classstingray_1_1SystemStats.html',1,'stingray']]]
];
