#ifndef STINGRAYKIT_PREPROCESSOR_BOOL_H
#define STINGRAYKIT_PREPROCESSOR_BOOL_H

// Copyright (c) 2011 - 2019, GS Group, https://github.com/GSGroup
// Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted,
// provided that the above copyright notice and this permission notice appear in all copies.
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
// WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.


#include <stingraykit/preprocessor/Cat.h>


/**
 * @addtogroup toolkit_macro
 * @{
 */

#define DETAIL_SECOND_ARG(_0, _1, ...) _1

#define DETAIL_NOT_IMPL(...) DETAIL_SECOND_ARG(__VA_ARGS__, 0, Dummy_)
#define DETAIL_NOT_0 ~, 1

#define STINGRAYKIT_NOT(A) DETAIL_NOT_IMPL(STINGRAYKIT_CAT(DETAIL_NOT_, A))

#define DETAIL_COMPL_0 1
#define DETAIL_COMPL_1 0

#define STINGRAYKIT_COMPL(A) STINGRAYKIT_CAT(DETAIL_COMPL_, A)


#define STINGRAYKIT_BOOL(A) STINGRAYKIT_COMPL(STINGRAYKIT_NOT(A))

#endif
